-- ACTIVIDAD: CAPITULO_03.
-- MATERIA: SISTEMAS DE BASE DE DATOS II.
-- NOMBRE: CRISITAN OMAR ALVARADO RODRIGUEZ.
-- GRUPO: 5"B".

-- B) Elabore 2 consultas sobre la base de datos “HOTEL�? para cada una de
-- las siguientes opciones:

-- LOWER:
SELECT LOWER(NOMBRE || ' ' || APATERNO || ' ' || AMATERNO) "EMPLEADO"
FROM EMPLEADO_COAR;

SELECT * FROM EMPLEADO_COAR WHERE LOWER(NOMBRE) = 'juan';

-- UPPER:
SELECT UPPER(NOMBRE || ' ' || APATERNO || ' ' || AMATERNO) "CLIENTE"
FROM CLIENTE_COAR;

SELECT * FROM CLIENTE_COAR WHERE UPPER(APATERNO) = 'ALVAREZ';

-- INITCAP:
SELECT INITCAP(NOMBRE || ' ' || APATERNO || ' ' || AMATERNO) "EMPLEADO"
FROM EMPLEADO_COAR;

SELECT INITCAP(NOMBRE) "NOMBRE DEL HOTEL"
FROM HOTEL_COAR;

-- CONCAT:
SELECT UPPER(CONCAT('EL HOTEL ', NOMBRE) || CONCAT(' SE CONSTRUYO EL ', FECHA_CONSTRUCCION)) 
"DETALLES HOTEL" FROM HOTEL_COAR;

SELECT UPPER(CONCAT('El cliente ', NOMBRE || ' ' || APATERNO) || 
       CONCAT(' tiene ', EDAD)) "Detalles Cliente"
FROM CLIENTE_COAR; 

SELECT CONCAT(NOMBRE, CONCAT(' ', CONCAT(APATERNO, CONCAT(' ', AMATERNO)))) 
"NOMBRE CLIENTE"FROM CLIENTE_COAR;

-- SUBSTR:
SELECT SUBSTR(NOMBRE, 1, 3) FROM CLIENTE_COAR;
SELECT SUBSTR(NOMBRE, -2, 4) FROM AGENCIA_COAR;

-- LENGTH:
SELECT LENGTH(NOMBRE) "LONGITUD NOMBRE EMPLEADO"
FROM EMPLEADO_COAR;

SELECT * FROM EMPLEADO_COAR WHERE LENGTH(NOMBRE) <= 7;

-- INSTR:
SELECT INSTR(NOMBRE, UPPER('a')) "Contiene 'a'?" FROM EMPLEADO_COAR;
SELECT INSTR(NOMBRE, 'H') FROM HOTEL_COAR;

-- LPAD | RPAD:
SELECT LPAD(NOMBRE, 10, '*') FROM EMPLEADO_COAR;
SELECT LPAD(SALARIO * 12, 10,'-') FROM EMPLEADO_COAR;

SELECT RPAD(FECHA_CONTRATACION, 10) FROM EMPLEADO_COAR;
SELECT RPAD(APATERNO, 15, '#') FROM EMPLEADO_COAR;

-- TRIM:
SELECT TRIM(TRAILING 'A' FROM NOMBRE) FROM EMPLEADO_COAR;
SELECT TRIM(BOTH 'A' FROM APATERNO) FROM EMPLEADO_COAR;

-- REPLACE:
SELECT REPLACE(SALARIO, 3000, 5000) FROM EMPLEADO_COAR;
SELECT REPLACE(EDAD, 25, 30) FROM CLIENTE_COAR;

-- ROUND:
SELECT ROUND(SALARIO, 2) FROM EMPLEADO_COAR;
SELECT ROUND(SUBTOTAL, -3) FROM RESERVACION_COAR;

-- TRUNC:
SELECT TRUNC(SALARIO, 1) FROM EMPLEADO_COAR;
SELECT TRUNC(SUBTOTAL, 5) FROM RESERVACION_COAR;

-- MOD:
SELECT MOD(SALARIO, 500) FROM EMPLEADO_COAR;
SELECT MOD(EDAD, 10) FROM CLIENTE_COAR;

-- ROUND PARA FECHAS:
SELECT FECHA_CONTRATACION,
       ROUND(FECHA_CONTRATACION, 'YEAR') 
FROM EMPLEADO_COAR;

SELECT FECHA_CONTRATACION,
       ROUND(FECHA_CONTRATACION, 'DAY') 
FROM EMPLEADO_COAR;

-- TRUNC PARA FECHAS:
SELECT FECHA_CONTRATACION,
       TRUNC(FECHA_CONTRATACION, 'MONTH') 
FROM EMPLEADO_COAR;

SELECT FECHA_CONSTRUCCION,
       TRUNC(FECHA_CONSTRUCCION, 'MM') 
FROM HOTEL_COAR;

-- OPERADORES ARTIMETICOS CON FECHA:
SELECT FECHA_CONTRATACION + 7 FROM EMPLEADO_COAR;
SELECT FECHA_CONSTRUCCION + 2 FROM HOTEL_COAR;

-- MONTHS_BETWEEN:
SELECT * FROM RESERVACION_COAR;
SELECT MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATACION) FROM EMPLEADO_COAR;
SELECT MONTHS_BETWEEN(FECHA_FIN, FECHA_INICIO) FROM RESERVACION_COAR;

-- ADD_MONTHS:
SELECT ADD_MONTHS(FECHA_CONTRATACION, 6) FROM EMPLEADO_COAR;
SELECT ADD_MONTHS(FECHA_FIN, 2) FROM RESERVACION_COAR;

-- NEXT_DAY:
SELECT NEXT_DAY(FECHA_CONTRATACION, 'VIERNES') FROM EMPLEADO_COAR;
SELECT NEXT_DAY(FECHA_INICIO, 'LUNES') FROM RESERVACION_COAR;

-- LAST_DAY:
SELECT LAST_DAY(FECHA_CONTRATACION) FROM EMPLEADO_COAR;
SELECT LAST_DAY(FECHA_FIN) FROM RESERVACION_COAR;
