      -- Practica 13: Consultas Hospital.
-- Materia: Sitemas de Base de Datos.
-- Alumno: Cristian Omar Alvarado Rodriguez.

-- 1: Consultar el nombre completo de los médicos que han realizado al menos una consulta.
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

SELECT ID_MEDICO, APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "MEDICO" 
FROM MEDICO_COAR WHERE ID_MEDICO IN (SELECT ID_MEDICO FROM CONSULTA_COAR);

-- 2: Consultar el nombre completo de los pacientes que han sido consultados.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CITA_COAR;
SELECT * FROM CONSULTA_COAR;

INSERT INTO PACIENTE_COAR VALUES(6,'GARCIA','LOPEZ','CARLOS','20/09/1991',30,'M','4236839543');

SELECT ID_PACIENTE, APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "PACIENTE"
FROM PACIENTE_COAR WHERE ID_PACIENTE IN (SELECT ID_PACIENTE FROM CITA_COAR
WHERE ID_PACIENTE IN (SELECT ID_PACIENTE FROM CONSULTA_COAR));

-- 3: Consultar el nombre completo de los pacientes que han sido consultados e incluir el nombre completo 
-- del médico y la fecha de la consulta.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       CS.FECHA "FECHA_CONSULTA"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     JOIN MEDICO_COAR M ON M.ID_MEDICO = CS.ID_MEDICO;

-- 4: Consultar nombre completo de los pacientes y el tipo de análisis que se le han realizado.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM TIPO_ANALISIS_COAR;
SELECT * FROM ANALISIS_CLINICO_COAR;

SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       TA.DESCRIPCION "TIPO_ANALISIS",
       AC.FECHA "FECHA_ANALISIS"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     JOIN ANALISIS_CLINICO_COAR AC ON CS.ID_PACIENTE = AC.ID_PACIENTE AND 
                                                     CS.FOLIO_CONSULTA = AC.FOLIO_CONSULTA
                     JOIN TIPO_ANALISIS_COAR TA ON AC.ID_TIPO_ANALISIS = TA.ID_TIPO_ANALISIS;                                                        

-- 5: Consultar el nombre completo de los pacientes que han sido hospitalizados.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM HOSPITALIZACION_COAR;

SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       H.DESCRIPCION "MOTIVO_HOSPITALIZACION",
       H.FECHA_INGRESO "FECHA_INGRESO",
       H.FECHA_EGRESO "FECHA_EGRESO"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     JOIN HOSPITALIZACION_COAR H ON CS.ID_PACIENTE = H.ID_PACIENTE AND 
                                                   CS.FOLIO_CONSULTA = H.FOLIO_CONSULTA;

-- 6: Consultar el nombre completo de todos los pacientes y en caso de que hayan generado alguna cita, 
-- mostrar la fecha de la cita y el nombre completo de la asistente que la generó.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM ASISTENTE_COAR;
SELECT * FROM CITA_COAR;

INSERT INTO PACIENTE_COAR VALUES(8,'HERNANDEZ','GARCIA','ALBERTO','20/09/1991',30,'M','4236839543');

SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       A.APATERNO || ' ' || A.AMATERNO || ' ' || A.NOMBRE "ASISTENTE",
       C.FECHA_HORA "FECHA_CITA"
FROM PACIENTE_COAR P LEFT OUTER JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     LEFT OUTER JOIN ASISTENTE_COAR A ON C.ID_ASISTENTE = A.ID_ASISTENTE;

-- 7: Consultar el nombre completo de los médicos y el total de consultas que han realizado.
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

SELECT M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       COUNT(*) "TOTAL_CONSULTAS"
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY M.APATERNO, M.AMATERNO, M.NOMBRE;

-- 8: Consultar el nombre de los médicos que no han realizado consultas.
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

SELECT ID_MEDICO,
       APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "MEDICO"
FROM MEDICO_COAR WHERE ID_MEDICO NOT IN (SELECT ID_MEDICO FROM CONSULTA_COAR);

-- 9: Consultar el nombre completo de los pacientes y el total de consultas que ha tenido cada uno.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CITA_COAR;
SELECT * FROM CONSULTA_COAR;

INSERT INTO CITA_COAR VALUES(3,2,'00000006',TO_DATE('13/05/2022 12:30:00 AM','DD/MM/YYYY HH:MI:SS AM'),'CITA POR GRIPA');
INSERT INTO CONSULTA_COAR VALUES(3,2,'00000006',3,5,1,'00000006','13/05/2022');

SELECT P.ID_PACIENTE,
       P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       COUNT(*) "TOTAL_CONSULTAS"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE;

-- 10: Consultar el nombre de los medicamentos que no se han recetado.
SELECT * FROM MEDICAMENTO_COAR;
SELECT * FROM RECETA_COAR;

SELECT ID_MEDICAMENTO,
       NOMBRE "MEDICAMENTO"
FROM MEDICAMENTO_COAR WHERE ID_MEDICAMENTO NOT IN (SELECT ID_MEDICAMENTO FROM RECETA_COAR);

-- 11: Consultar el nombre completo de los pacientes que más consultas han tenido.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CITA_COAR;
SELECT * FROM CONSULTA_COAR;

-- PASO 1: OBTENER EL TOTAL DE CONSULTAS POR PACIENTE
SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       COUNT(*) "TOTAL_CONSULTAS"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE;

-- PASO 2: OBTENER EL VALOR MAS ALTO DEL TOTAL DE CONSULTAS POR PACIENTE
SELECT MAX(COUNT(*)) "TOTAL_CONSULTAS"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       COUNT(*) "TOTAL_CONSULTAS"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE);

-- 12: Consultar el nombre completo de los médicos que más consultas han tenido.
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

-- PASO 1: OBTENER EL TOTAL DE CONSULTAS POR MEDICO
SELECT M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       COUNT(*) "TOTAL_CONSULTAS"
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY M.APATERNO, M.AMATERNO, M.NOMBRE;

-- PASO 2: OBTENER EL VALOR MAS ALTO DEL TOTAL DE CONSULTAS POR MEDICO
SELECT MAX(COUNT(*)) "TOTAL_CONSULTAS"
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY M.APATERNO, M.AMATERNO, M.NOMBRE;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       COUNT(*) "TOTAL_CONSULTAS"
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY M.APATERNO, M.AMATERNO, M.NOMBRE HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY M.APATERNO, M.AMATERNO, M.NOMBRE);

-- 13: Consultar el nombre completo de los pacientes que más han sido hospitalizados.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CONSULTA_COAR;
SELECT * FROM CITA_COAR;
SELECT * FROM HOSPITALIZACION_COAR;

INSERT INTO HOSPITALIZACION_COAR VALUES(3,2,'00000006',3,5,1,'00000006',1,3,'00000006','HOSPITALIZACION POR FRACTURA','12/05/2022','16/05/2022');

-- PASO 1: OBTENER EL TOTAL DE HOSPITALIZACIONES POR PACIENTE
SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       COUNT(*) "TOTAL_HOSPITALIZACIONES"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     JOIN HOSPITALIZACION_COAR H ON H.ID_PACIENTE = C.ID_PACIENTE AND H.FOLIO_CITA = C.FOLIO_CITA 
                                                                                  AND H.FOLIO_CONSULTA = CS.FOLIO_CONSULTA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE;

-- PASO 2: OBTENER EL VALOR MAS ALTO DEL TOTAL DE HOSPITALIZACIONES POR PACIENTE
SELECT MAX(COUNT(*)) "TOTAL_HOSPITALIZACIONES"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     JOIN HOSPITALIZACION_COAR H ON H.ID_PACIENTE = C.ID_PACIENTE AND H.FOLIO_CITA = C.FOLIO_CITA 
                                                                                  AND H.FOLIO_CONSULTA = CS.FOLIO_CONSULTA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       COUNT(*) "TOTAL_HOSPITALIZACIONES"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     JOIN HOSPITALIZACION_COAR H ON H.ID_PACIENTE = C.ID_PACIENTE AND H.FOLIO_CITA = C.FOLIO_CITA 
                                                                                  AND H.FOLIO_CONSULTA = CS.FOLIO_CONSULTA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE HAVING COUNT(*) = (SELECT MAX(COUNT(*)) 
FROM PACIENTE_COAR P JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = C.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     JOIN HOSPITALIZACION_COAR H ON H.ID_PACIENTE = C.ID_PACIENTE AND H.FOLIO_CITA = C.FOLIO_CITA 
                                                                                  AND H.FOLIO_CONSULTA = CS.FOLIO_CONSULTA
GROUP BY P.ID_PACIENTE, P.APATERNO, P.AMATERNO, P.NOMBRE);

-- 14: Consultar el nombre completo de las enfermeras que más pacientes han atendido.
SELECT * FROM ENFERMERA_COAR;
SELECT * FROM HOSPITALIZACION_COAR;

-- PASO 1: OBTENER EL TOTAL DE PACIENTES ATENDIDOS POR CADA ENFERMERA
SELECT E.APATERNO || ' ' || E.AMATERNO || ' ' || E.NOMBRE "ENFERMERA",
       COUNT(*) "TOTAL_PACIENTES_ATENDIDOS"
FROM ENFERMERA_COAR E JOIN HOSPITALIZACION_COAR H ON H.ID_ENFERMERA = E.ID_ENFERMERA
GROUP BY E.ID_ENFERMERA, E.APATERNO, E.AMATERNO, E.NOMBRE;

-- PASO 2: OBTENER EL VALOR MAS ALTO DEL TOTAL DE PACIENTES ATENDIDOS POR CADA ENFERMERA
SELECT MAX(COUNT(*)) "TOTAL_PACIENTES_ATENDIDOS"
FROM ENFERMERA_COAR E JOIN HOSPITALIZACION_COAR H ON H.ID_ENFERMERA = E.ID_ENFERMERA
GROUP BY E.ID_ENFERMERA, E.APATERNO, E.AMATERNO, E.NOMBRE;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT E.APATERNO || ' ' || E.AMATERNO || ' ' || E.NOMBRE "ENFERMERA",
       COUNT(*) "TOTAL_PACIENTES_ATENDIDOS"
FROM ENFERMERA_COAR E JOIN HOSPITALIZACION_COAR H ON H.ID_ENFERMERA = E.ID_ENFERMERA
GROUP BY E.ID_ENFERMERA, E.APATERNO, E.AMATERNO, E.NOMBRE HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM ENFERMERA_COAR E JOIN HOSPITALIZACION_COAR H ON H.ID_ENFERMERA = E.ID_ENFERMERA
GROUP BY E.ID_ENFERMERA, E.APATERNO, E.AMATERNO, E.NOMBRE);

-- 15: Consultar al médico del año (El médico que más consultas realizó en un determinado año).
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

-- PASO 1: OBTENER EL TOTAL DE CONSULTAS REALIZADAS POR CADA MEDICO EN EL AÑO 2022 (22)
SELECT M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       COUNT(*) "TOTAL_CONSULTAS_2022"
FROM MEDICO_COAR M JOIN CONSULTA_COAR CS ON CS.ID_MEDICO = M.ID_MEDICO WHERE 
CS.FECHA BETWEEN TO_DATE('01/01/2022', 'DD/MM/YYYY') AND TO_DATE('31/12/2022', 'DD/MM/YYYY')
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE;

-- PASO 2: OBTENER EL VALOR MAS ALTO DEL TOTAL DE CONSULTAS REALIZADAS POR CADA MEDICO EN EL AÑO 2022 (22)
SELECT MAX(COUNT(*)) "TOTAL_CONSULTAS_2022"
FROM MEDICO_COAR M JOIN CONSULTA_COAR CS ON CS.ID_MEDICO = M.ID_MEDICO WHERE CS.FECHA 
BETWEEN TO_DATE('01/01/2022', 'DD/MM/YYYY') AND TO_DATE('31/12/2022', 'DD/MM/YYYY')
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       COUNT(*) "TOTAL_CONSULTAS_2022"
FROM MEDICO_COAR M JOIN CONSULTA_COAR CS ON CS.ID_MEDICO = M.ID_MEDICO WHERE 
CS.FECHA BETWEEN TO_DATE('01/01/2022', 'DD/MM/YYYY') AND TO_DATE('31/12/2022', 'DD/MM/YYYY')
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM MEDICO_COAR M JOIN CONSULTA_COAR CS ON CS.ID_MEDICO = M.ID_MEDICO WHERE
CS.FECHA BETWEEN TO_DATE('01/01/2022', 'DD/MM/YYYY') AND TO_DATE('31/12/2022', 'DD/MM/YYYY')
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE);

-- 16: Consultar el nombre completo de los pacientes que no se han realizado análisis clínicos.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CONSULTA_COAR;
SELECT * FROM ANALISIS_CLINICO_COAR;

SELECT ID_PACIENTE, APATERNO, AMATERNO, NOMBRE FROM PACIENTE_COAR
WHERE ID_PACIENTE NOT IN (SELECT ID_PACIENTE FROM CITA_COAR WHERE ID_PACIENTE IN 
(SELECT ID_PACIENTE FROM CONSULTA_COAR WHERE ID_PACIENTE IN 
(SELECT ID_PACIENTE FROM ANALISIS_CLINICO_COAR)));

-- 17: Consultar el nombre completo de los pacientes que sacaron cita, pero no asistieron a la consulta.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CITA_COAR;
SELECT * FROM CONSULTA_COAR;

INSERT INTO PACIENTE_COAR VALUES(7,'VAZQUEZ','ROMERO','KAREN','20/03/1997',25,'F','4924567892');
INSERT INTO CITA_COAR VALUES(6,1,'00000007',TO_DATE('16/05/2022 01:30:00 PM','DD/MM/YYYY HH:MI:SS PM'),'MALESTAR ESTOMACAL');
INSERT INTO CITA_COAR VALUES(7,3,'00000008',TO_DATE('17/05/2022 12:30:00 PM','DD/MM/YYYY HH:MI:SS PM'),'DOLOR DE CABEZA');

SELECT P.ID_PACIENTE, 
      P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON C.ID_PACIENTE = P.ID_PACIENTE
WHERE C.ID_PACIENTE NOT IN (SELECT ID_PACIENTE FROM CONSULTA_COAR);

-- 18: Consultar el nombre completo de todos los pacientes y en caso de que haya sido consultados mostrar 
-- la fecha de consulta y en caso de que hayan sido recetados, mostrar el nombre del medicamento que fue recetado.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CONSULTA_COAR;
SELECT * FROM RECETA_COAR;
SELECT * FROM MEDICAMENTO_COAR;

SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       CS.FECHA "FECHA_CONSULTA",
       M.NOMBRE "MEDICAMENTO RECETADO"
FROM PACIENTE_COAR P LEFT OUTER JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     LEFT OUTER JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = P.ID_PACIENTE AND CS.FOLIO_CITA = C.FOLIO_CITA
                     LEFT OUTER JOIN RECETA_COAR R ON R.ID_PACIENTE = P.ID_PACIENTE AND R.FOLIO_CONSULTA = CS.FOLIO_CONSULTA
                     LEFT OUTER JOIN MEDICAMENTO_COAR M ON M.ID_MEDICAMENTO = R.ID_MEDICAMENTO;

-- 19: Consultar el nombre completo de la asistente del mes (La asistente que más cita generó en un determinado mes).
SELECT * FROM ASISTENTE_COAR;
SELECT * FROM CITA_COAR;

-- PASO 1: OBTENER EL TOTAL DE CITAS GENERADAS POR CADA ASISTENTE EN EL MES DE MAYO (05)
SELECT A.APATERNO || ' ' || A.AMATERNO || ' ' || A.NOMBRE "ASISTENTE",
       COUNT(*) "TOTAL_CITAS_MES_MAYO"
FROM ASISTENTE_COAR A JOIN CITA_COAR C ON C.ID_ASISTENTE = A.ID_ASISTENTE WHERE C.FECHA_HORA
BETWEEN TO_DATE('01/05/2022', 'DD/MM/YYYY') AND TO_DATE('31/05/2022', 'DD/MM/YYYY')
GROUP BY A.ID_ASISTENTE, A.APATERNO, A.AMATERNO, A.NOMBRE;

-- PASO 2: OBTENER EL VALOR MAS ALTO DEL TOTAL DE CITAS GENERADAS POR CADA ASISTENTE EN EL MES DE MAYO (05)
SELECT MAX(COUNT(*)) "TOTAL_CITAS_MES_MAYO"
FROM ASISTENTE_COAR A JOIN CITA_COAR C ON C.ID_ASISTENTE = A.ID_ASISTENTE WHERE C.FECHA_HORA
BETWEEN TO_DATE('01/05/2022', 'DD/MM/YYYY') AND TO_DATE('31/05/2022', 'DD/MM/YYYY')
GROUP BY A.ID_ASISTENTE, A.APATERNO, A.AMATERNO, A.NOMBRE;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT A.APATERNO || ' ' || A.AMATERNO || ' ' || A.NOMBRE "ASISTENTE",
       COUNT(*) "TOTAL_CITAS_MES_MAYO"
FROM ASISTENTE_COAR A JOIN CITA_COAR C ON C.ID_ASISTENTE = A.ID_ASISTENTE WHERE C.FECHA_HORA 
BETWEEN TO_DATE('01/05/2022', 'DD/MM/YYYY') AND TO_DATE('31/05/2022', 'DD/MM/YYYY')
GROUP BY A.ID_ASISTENTE, A.APATERNO, A.AMATERNO, A.NOMBRE HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM ASISTENTE_COAR A JOIN CITA_COAR C ON C.ID_ASISTENTE = A.ID_ASISTENTE WHERE C.FECHA_HORA
BETWEEN TO_DATE('01/05/2022', 'DD/MM/YYYY') AND TO_DATE('31/05/2022', 'DD/MM/YYYY')
GROUP BY A.ID_ASISTENTE, A.APATERNO, A.AMATERNO, A.NOMBRE);

-- 20: Consultar el nombre completo del médico que menos consultas ha tenido.
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

-- PASO 1: OBTENER EL TOTAL DE CONSULTAS POR CADA MEDICO
SELECT M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       COUNT(*) "TOTAL_CONSULTAS"
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON C.ID_MEDICO = M.ID_MEDICO
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE;

-- PASO 2: OBTENER EL VALOR MAS BAJO DEL TOTAL DE CONSULTAS POR CADA MEDICO 
SELECT MIN(COUNT(*)) "TOTAL_CONSULTAS"
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON C.ID_MEDICO = M.ID_MEDICO
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE "MEDICO",
       COUNT(*) "TOTAL_CONSULTAS"
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON C.ID_MEDICO = M.ID_MEDICO
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE HAVING COUNT(*) = (SELECT MIN(COUNT(*))
FROM MEDICO_COAR M JOIN CONSULTA_COAR C ON C.ID_MEDICO = M.ID_MEDICO
GROUP BY M.ID_MEDICO, M.APATERNO, M.AMATERNO, M.NOMBRE);

-- 21: Redacte 10 enunciados y elabore las sentencias necesarias para dar respuesta a dichos enunciados.

-- 1: CONSULTAR EL NOMBRE COMPLETO DEL LOS ASISTENTES QUE NO HAN GENERADO NINGUNA CITA.
SELECT * FROM ASISTENTE_COAR;
SELECT * FROM CITA_COAR;

SELECT ID_ASISTENTE,  
       APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "ASISTENTE"
FROM ASISTENTE_COAR WHERE ID_ASISTENTE NOT IN (SELECT ID_ASISTENTE FROM CITA_COAR);

-- 2: CONSULTAR EL NOMBRE COMPLETO DEL LOS PACIENTES QUE PAGARON POR SU CONSULTA Y MOSTRAR LA CANTIDAD PAGADA.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CONSULTA_COAR;
SELECT * FROM PAGO_CONSULTA_COAR;

SELECT P.ID_PACIENTE,
       P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       CS.FECHA "FECHA_CONSULTA",
       PC.FECHA "FECHA_PAGO",
       PC.SUBTOTAL "CANTIDAD_PAGADA"
FROM PACIENTE_COAR P JOIN CITA_COAR C ON C.ID_PACIENTE = P.ID_PACIENTE
                     JOIN CONSULTA_COAR CS ON C.ID_PACIENTE = CS.ID_PACIENTE AND C.FOLIO_CITA = CS.FOLIO_CITA
                     JOIN PAGO_CONSULTA_COAR PC ON CS.FOLIO_CITA = PC.FOLIO_CITA AND CS.ID_PACIENTE = PC.ID_PACIENTE 
                                                                            AND CS.FOLIO_CONSULTA = PC.FOLIO_CONSULTA;

-- 3: CONSULTAR EL NOMBRE DEL MEDICAMENTO MAS RECETADO.
SELECT * FROM MEDICAMENTO_COAR;
SELECT * FROM RECETA_COAR;

SELECT M.NOMBRE "MEDICAMENTO",
       COUNT(*) "TOTAL_RECETAS"
FROM MEDICAMENTO_COAR M JOIN RECETA_COAR R ON R.ID_MEDICAMENTO = M.ID_MEDICAMENTO
GROUP BY M.ID_MEDICAMENTO, M.NOMBRE HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM MEDICAMENTO_COAR M JOIN RECETA_COAR R ON R.ID_MEDICAMENTO = M.ID_MEDICAMENTO
GROUP BY M.ID_MEDICAMENTO, M.NOMBRE);

-- 4: Consultar el nombre completo de todos los pacientes y en caso de que haya sido consultados mostrar la fecha 
-- de consulta y en caso de que tenga un expediente medico mostrar sus observaciones y alergias.
SELECT * FROM PACIENTE_COAR;
SELECT * FROM CONSULTA_COAR;
SELECT * FROM EXPEDIENTE_COAR;

SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       CS.FECHA "FECHA_CONSULTA",
       E.OBSERVACIONES,
       E.ALERGIAS   
FROM PACIENTE_COAR P LEFT OUTER JOIN CITA_COAR C ON P.ID_PACIENTE = C.ID_PACIENTE
                     LEFT OUTER JOIN CONSULTA_COAR CS ON CS.ID_PACIENTE = P.ID_PACIENTE 
                                                        AND CS.FOLIO_CITA = C.FOLIO_CITA
                     LEFT OUTER JOIN EXPEDIENTE_COAR E ON E.ID_PACIENTE = P.ID_PACIENTE  
                                                        AND CS.FOLIO_CITA = E.FOLIO_CITA 
                                                        AND CS.FOLIO_CONSULTA = E.FOLIO_CONSULTA;

-- 5: Consultar el nombre completo de todos los pacientes que sean mujer.
SELECT * FROM PACIENTE_COAR;

SELECT ID_PACIENTE,
       APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "PACIENTE" 
FROM PACIENTE_COAR P WHERE P.SEXO = 'F';

-- 6: Consultar el nombre completo de las enfermeras que no han atendido a ningun paciente.
SELECT * FROM ENFERMERA_COAR;
SELECT * FROM HOSPITALIZACION_COAR;

SELECT ID_ENFERMERA,
       APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "ENFERMERA"
FROM ENFERMERA_COAR WHERE ID_ENFERMERA NOT IN (SELECT ID_ENFERMERA FROM HOSPITALIZACION_COAR);

-- 7: Consultar la especialidad de los medicos que no han atendido a ningun paciente.
SELECT * FROM MEDICO_COAR;
SELECT * FROM CONSULTA_COAR;

SELECT ID_MEDICO,
       APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "MEDICO",
       ESPECIALIDAD
FROM MEDICO_COAR WHERE ID_MEDICO NOT IN (SELECT ID_MEDICO FROM CONSULTA_COAR);

-- 8: Consultar el nombre completo de los pacientes que han sido hospitalizados en un determinado mes y año (MAYO 2022).
SELECT * FROM PACIENTE_COAR;
SELECT * FROM HOSPITALIZACION_COAR;

SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE "PACIENTE",
       H.FECHA_INGRESO "FECHA_INGRESO"
FROM PACIENTE_COAR P JOIN HOSPITALIZACION_COAR H ON P.ID_PACIENTE = H.ID_PACIENTE
WHERE TO_CHAR(H.FECHA_INGRESO, 'MM') = '05' AND TO_CHAR(H.FECHA_INGRESO, 'YYYY') = '2022';

-- 9: Consultar el tipo de analisis clinico mas solicitado por los pacientes.
SELECT * FROM TIPO_ANALISIS_COAR;
SELECT * FROM ANALISIS_CLINICO_COAR;

-- PASO 1: OBTENER EL TOTAL DE LA CANTIDAD DE ANALISIS CLINICOS POR CADA TIPO DE ANALISIS CLINICO
SELECT TA.ID_TIPO_ANALISIS,
       TA.DESCRIPCION "TIPO_ANALISIS",
       COUNT(*) "TOTAL"
FROM TIPO_ANALISIS_COAR TA JOIN ANALISIS_CLINICO_COAR AC ON TA.ID_TIPO_ANALISIS = AC.ID_TIPO_ANALISIS
GROUP BY TA.ID_TIPO_ANALISIS, TA.DESCRIPCION;

-- PASO 2: OBTENER EL VALOR MAS ALTO DEL PASO 1
SELECT MAX(COUNT(*)) "TOTAL"
FROM TIPO_ANALISIS_COAR TA JOIN ANALISIS_CLINICO_COAR AC ON TA.ID_TIPO_ANALISIS = AC.ID_TIPO_ANALISIS
GROUP BY TA.ID_TIPO_ANALISIS, TA.DESCRIPCION;

-- PASO 3: INTEGRAR EN UNA SOLA CONSULTA EL PASO 1 Y EL PASO 2 (HAVING)
SELECT TA.ID_TIPO_ANALISIS,
       TA.DESCRIPCION "TIPO_ANALISIS",
       COUNT(*) "TOTAL"
FROM TIPO_ANALISIS_COAR TA JOIN ANALISIS_CLINICO_COAR AC ON TA.ID_TIPO_ANALISIS = AC.ID_TIPO_ANALISIS
GROUP BY TA.ID_TIPO_ANALISIS, TA.DESCRIPCION HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM TIPO_ANALISIS_COAR TA JOIN ANALISIS_CLINICO_COAR AC ON TA.ID_TIPO_ANALISIS = AC.ID_TIPO_ANALISIS
GROUP BY TA.ID_TIPO_ANALISIS, TA.DESCRIPCION);

-- 10: Consultar el sueldo anual de las enfermeras.
SELECT * FROM ENFERMERA_COAR;

ALTER TABLE ENFERMERA_COAR ADD SUELDO NUMBER(8,2);

UPDATE ENFERMERA_COAR SET SUELDO = 10000 WHERE ID_ENFERMERA = 1;
UPDATE ENFERMERA_COAR SET SUELDO = 12000 WHERE ID_ENFERMERA = 2;
UPDATE ENFERMERA_COAR SET SUELDO = 15000 WHERE ID_ENFERMERA = 3;
UPDATE ENFERMERA_COAR SET SUELDO = 10000 WHERE ID_ENFERMERA = 4;
UPDATE ENFERMERA_COAR SET SUELDO = 12000 WHERE ID_ENFERMERA = 5;

SELECT APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "ENFERMERA",
       SUELDO "SUELDO_MENSUAL",
       SUELDO * 12 "SUELDO_ANUAL"
FROM ENFERMERA_COAR;

COMMIT;