--PRACTICA #10 SEGUROS DE AUTOMOVILES
--Autor: Cristian Omar Alvarado Rodriguez
--Materia: Sistemas De Base De Datos

-- Tabla CLIENTE
CREATE TABLE CLIENTE_COAR(
   ID_CLIENTE NUMBER(5) CONSTRAINT CLIENTE_COAR_PK PRIMARY KEY,
   APATERNO VARCHAR2(35) CONSTRAINT CLI_COAR_AP_NN NOT NULL,
   AMATERNO VARCHAR2(35),
   NOMBRE VARCHAR2(50) CONSTRAINT CLI_COAR_NOM_NN NOT NULL,
   EMAIL VARCHAR2(50),
   MUNICIPIO VARCHAR2(30) DEFAULT 'Zacatecas'
);

-- Insertar datos en la tabla CLIENTE_COAR
INSERT INTO CLIENTE_COAR VALUES(1,'PEREZ','LOPEZ','JUAN','JUAN@GMAIL.COM', 'ZACATECAS');
INSERT INTO CLIENTE_COAR VALUES(2,'RODRIGUEZ','ALVARADO','OMAR','OMAR@GMAIL.COM', 'ZACATECAS');
INSERT INTO CLIENTE_COAR VALUES(3,'FLORES', 'DIAZ', 'MARIO', 'MARIO@GMAIL.COM', 'ZACATECAS');
INSERT INTO CLIENTE_COAR VALUES(4,'GARCIA','PEREZ','ANA','ANA@GMAIL.COM', 'ZACATECAS');
INSERT INTO CLIENTE_COAR VALUES(5,'LOPEZ','TORRES','CARLOS','CARLOS@GMAIL.COM', 'ZACATECAS');

SELECT * FROM CLIENTE_COAR;

-- Tabla AUTOMOVIL
CREATE TABLE AUTOMOVIL_COAR(
   NUM_SERIE CHAR(8) CONSTRAINT AUTOMOVIL_COAR_PK PRIMARY KEY,
   MARCA VARCHAR2(50) CONSTRAINT AUT_COAR_MARCA_NN NOT NULL,
   MODELO NUMBER(4) CONSTRAINT AUT_COAR_MOD_NN NOT NULL,
   LINEA VARCHAR2(50) CONSTRAINT AUT_COAR_LINEA_NN NOT NULL,
   COLOR VARCHAR2(35) CONSTRAINT AUT_COAR_COLOR_NN NOT NULL,
   COSTO NUMBER(7) CONSTRAINT AUT_COAR_COSTO_NN NOT NULL 
                   CONSTRAINT AUT_COAR_COSTO_CK CHECK (COSTO > 0)
);

-- Insertar datos en la tabla AUTOMOVIL_COAR
INSERT INTO AUTOMOVIL_COAR VALUES('00000001','Toyota','2020','hilux','negro','600000');
INSERT INTO AUTOMOVIL_COAR VALUES('00000002','VW','2020','Beatle','negro','300000');
INSERT INTO AUTOMOVIL_COAR VALUES('00000003','Chevrolet','2020','aveo','negro','400000');
INSERT INTO AUTOMOVIL_COAR VALUES('00000004','Nissan','2020','tsuru','rojo','800000');
INSERT INTO AUTOMOVIL_COAR VALUES('00000005','Nissan','2020','versa','azul','200000');
INSERT INTO AUTOMOVIL_COAR VALUES('00000006','Lamborghini','2020','Huracan','Verde','3000000');

SELECT * FROM AUTOMOVIL_COAR;

-- Tabla AGENTE_VENTAS  
CREATE TABLE AGENTE_VENTAS_COAR(
   ID_AGENTE NUMBER(5) CONSTRAINT AGENTE_COAR_PK PRIMARY KEY,
   APATERNO VARCHAR2(35) CONSTRAINT AGENTE_COAR_AP_NN NOT NULL,
   AMATERNO VARCHAR2(35),
   NOMBRE VARCHAR2(50) CONSTRAINT AGENTE_COAR_NOM_NN NOT NULL,
   TELEFONO VARCHAR2(10) CONSTRAINT AGENTE_COAR_TEL_NN NOT NULL,
   EMAIL VARCHAR2(50),
   COMISION NUMBER(2) CONSTRAINT AGENTE_COAR_COM_NN NOT NULL
);

-- Insertar datos en la tabla AGENTE_VENTAS_COAR
INSERT INTO AGENTE_VENTAS_COAR VALUES(1,'GARCIA','LOPEZ', 'JUAN','4925265345','JUAN@GMAIL.COM', 10);
INSERT INTO AGENTE_VENTAS_COAR VALUES(2,'ALVAREZ','GONZALEZ', 'OMAR','4925265345','OMAR@GMAIL.COM', 20);
INSERT INTO AGENTE_VENTAS_COAR VALUES(3,'LOPEZ','PEREZ', 'JOSE','4883453456', 'JOSE@GMAIL.COM', 15);
INSERT INTO AGENTE_VENTAS_COAR VALUES(4,'DIAZ','FLORES', 'MARIO','4924563456', 'MARIO@GMAIL.COM', 25);
INSERT INTO AGENTE_VENTAS_COAR VALUES(5,'PEREZ','GARCIA', 'ANA','4925265345','ANA@GMAIL.COM', 30);

SELECT * FROM AGENTE_VENTAS_COAR;

COMMIT;

-- Tabla AJUSTADOR
CREATE TABLE AJUSTADOR_COAR(
   ID_AJUSTADOR NUMBER(5) CONSTRAINT AJUSTADOR_COAR_PK PRIMARY KEY,
   APATERNO VARCHAR2(35) CONSTRAINT AJUS_COAR_AP_NN NOT NULL,
   AMATERNO VARCHAR2(35),
   NOMBRE VARCHAR2(50) CONSTRAINT AJUS_COAR_NOM_NN NOT NULL,
   TELEFONO VARCHAR2(10),
   EMAIL VARCHAR2(50) 
);

-- Insertar datos en la tabla AJUSTADOR_COAR
INSERT INTO AJUSTADOR_COAR VALUES(1,'TORRES','GONZALEZ', 'PEDRO','4925265345','PEDRO@GMAIL.COM');
INSERT INTO AJUSTADOR_COAR VALUES(2,'LOPEZ','GARCIA', 'CRISTIAN','4924729534','CRIS@GMAIL.COM');
INSERT INTO AJUSTADOR_COAR VALUES(3,'RODRIGUEZ','FLORES', 'JUAN','4926485829','JUAN@GMAIL.COM');
INSERT INTO AJUSTADOR_COAR VALUES(4,'DIAZ','MARTINEZ', 'OSCAR','4677684345','OSCAR@GMAIL.COM');
INSERT INTO AJUSTADOR_COAR VALUES(5,'PEREZ','FLORES', 'MARIA','4926783842','MARIA@GMAIL.COM');

SELECT * FROM AJUSTADOR_COAR;

COMMIT;

-- Tabla TIPO_SEGURO
CREATE TABLE TIPO_SEGURO_COAR(
   ID_TIPO_SEGURO NUMBER(2) CONSTRAINT TIPO_SEGURO_COAR_PK PRIMARY KEY,
   DESCRIPCION VARCHAR2(120) CONSTRAINT TS_COAR_DES_NN NOT NULL,
   COSTO_ANUAL NUMBER(8,2) CONSTRAINT TS_COAR_COA_NN NOT NULL
);

-- Insertar datos en la tabla TIPO_SEGURO_COAR
INSERT INTO TIPO_SEGURO_COAR VALUES(1,'DAÑOS MATERIALES', 4000);
INSERT INTO TIPO_SEGURO_COAR VALUES(2,'ROBO TOTAL', 5000);
INSERT INTO TIPO_SEGURO_COAR VALUES(3,'GASTOS MÉDICOS OCUPANTES', 4000);
INSERT INTO TIPO_SEGURO_COAR VALUES(4,'ARRASTRE DE REMOLQUE', 2000);
INSERT INTO TIPO_SEGURO_COAR VALUES(5,'RESPONSABILIDAD CIVIL POR DAÑOS A TERCEROS', 10000);

SELECT * FROM TIPO_SEGURO_COAR;

-- Tabla TIPO_ACCIDENTE
CREATE TABLE TIPO_ACCIDENTE_COAR(
   ID_TIPO_ACCIDENTE NUMBER(2) CONSTRAINT TIPO_ACCIDENTE_COAR_PK PRIMARY KEY,
   DESCRIPCION VARCHAR2(120) CONSTRAINT TA_COAR_DES_NN NOT NULL,
   NIVEL_GRAVEDAD VARCHAR2(15) CONSTRAINT TA_COAR_NIVG_NN NOT NULL
);

-- Insertar datos en la tabla TIPO_ACCIDENTE_COAR
INSERT INTO TIPO_ACCIDENTE_COAR VALUES(1,'CHOQUE DE VEHICULO', 'MEDIO');
INSERT INTO TIPO_ACCIDENTE_COAR VALUES(2,'ROBO DE VEHICULO', 'ALTO');
INSERT INTO TIPO_ACCIDENTE_COAR VALUES(3,'COLISIONES FRONTALES', 'MEDIO');
INSERT INTO TIPO_ACCIDENTE_COAR VALUES(4,'COLISIONES TRASERAS', 'BAJO');
INSERT INTO TIPO_ACCIDENTE_COAR VALUES(5,'COLISIONES LATERALES', 'MEDIO');

SELECT * FROM TIPO_ACCIDENTE_COAR;

COMMIT;

-- Tabla TALLER
CREATE TABLE TALLER_COAR(
   ID_TALLER NUMBER(2) CONSTRAINT TALLER_COAR_PK PRIMARY KEY,
   NOMBRE VARCHAR2(120) CONSTRAINT TALL_COAR_NOM_NN NOT NULL,
   UBICACION VARCHAR2(150) CONSTRAINT TALL_COAR_UBI_NN NOT NULL,
   TELEFONO VARCHAR2(10)
);

-- Insertar datos en la tabla TALLER_COAR
INSERT INTO TALLER_COAR VALUES(1,'H HERNANDEZ', 'AV. PASEO DE LA REFORMA', '4925265345');
INSERT INTO TALLER_COAR VALUES(2,'AUTO-MECANICA', 'AV. SAN MARCOS 201, ZACATECAS, ZAC', '4929240274');
INSERT INTO TALLER_COAR VALUES(3,'TALLER MEC�?NICO EL COLOR�?N', 'HÉROES DE LA REFORMA 110, ZACATECAS, ZAC', '4929246900');
INSERT INTO TALLER_COAR VALUES(4,'TALLLER REPARACIONES', 'DE LAS ANIMAS 12, LOS ANGELES, GUADALUPE, ZAC', '4929269183');
INSERT INTO TALLER_COAR VALUES(5,'GARAGE TALLER', 'NETZAHUALCÓYOTL 110, BUENOS AIRES, ZACATECAS, ZAC', '4929265345');

SELECT * FROM TALLER_COAR;

COMMIT;

-- Tabla de relacion CLIENTE_AUTOMOVIL
CREATE TABLE CLIENTE_AUTOMOVIL_COAR(
    ID_CLIENTE NUMBER(5),
    NUM_SERIE CHAR(8),
    FECHA_ASIGNACION DATE,
    CONSTRAINT CLIENTE_AUTOMOVIL_COAR_PK PRIMARY KEY (ID_CLIENTE,NUM_SERIE),
    CONSTRAINT CLICOAR_CLIAUTCOAR_FK FOREIGN KEY (ID_CLIENTE) 
                                           REFERENCES CLIENTE_COAR(ID_CLIENTE),
    CONSTRAINT AUTCOAR_CLIAUTCOAR_FK FOREIGN KEY (NUM_SERIE) 
                                           REFERENCES AUTOMOVIL_COAR(NUM_SERIE)
);

-- Insertar datos en la tabla CLIENTE_AUTOMOVIL_COAR
INSERT INTO CLIENTE_AUTOMOVIL_COAR VALUES(1,'00000001','29/04/22');
INSERT INTO CLIENTE_AUTOMOVIL_COAR VALUES(2,'00000003','30/04/22');
INSERT INTO CLIENTE_AUTOMOVIL_COAR VALUES(3,'00000002','03/05/22');
INSERT INTO CLIENTE_AUTOMOVIL_COAR VALUES(4,'00000004','04/05/22');
INSERT INTO CLIENTE_AUTOMOVIL_COAR VALUES(5,'00000005','05/05/22');

SELECT * FROM CLIENTE_AUTOMOVIL_COAR;

COMMIT;

-- Tabla de relacion POLIZA
CREATE TABLE POLIZA_COAR(
    ID_CLIENTE NUMBER(5),
    NUM_SERIE CHAR(8),
    ID_AGENTE NUMBER(5),
    ID_TIPO_SEGURO NUMBER(2),
    FOLIO CHAR(8),
    FECHA_E DATE CONSTRAINT POL_COAR_FE_NN NOT NULL,
    FECHA_I DATE CONSTRAINT POL_COAR_FI_NN NOT NULL,
    FECHA_F DATE CONSTRAINT POL_COAR_FF_NN NOT NULL,
    COSTO NUMBER(8,2) CONSTRAINT POL_COAR_COS_NN NOT NULL, 
    CONSTRAINT POLIZA_COAR_PK PRIMARY KEY (ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,FOLIO),
    CONSTRAINT CLIAUTCOAR_POLCOAR_FK FOREIGN KEY (ID_CLIENTE,NUM_SERIE) 
                                           REFERENCES CLIENTE_AUTOMOVIL_COAR(ID_CLIENTE,NUM_SERIE),
    CONSTRAINT AGENTECOAR_POLCOAR_FK FOREIGN KEY (ID_AGENTE) REFERENCES AGENTE_VENTAS_COAR(ID_AGENTE),
    CONSTRAINT TSCOAR_POLCOAR_FK FOREIGN KEY (ID_TIPO_SEGURO) REFERENCES TIPO_SEGURO_COAR(ID_TIPO_SEGURO)
);

-- Insertar datos en la tabla POLIZA_COAR
INSERT INTO POLIZA_COAR VALUES (1,'00000001',1,1,'00000001','29/04/22','01/05/22','01/05/23',5000);
INSERT INTO POLIZA_COAR VALUES (1,'00000001',1,2,'00000002','29/04/22','01/05/22','01/05/23',3000);
INSERT INTO POLIZA_COAR VALUES (1,'00000001',3,3,'00000003','29/04/22','01/05/22','01/05/23',2000);
INSERT INTO POLIZA_COAR VALUES (2,'00000002',2,4,'00000004','30/04/22','01/05/22','01/05/23',5000);
INSERT INTO POLIZA_COAR VALUES (3,'00000002',4,3,'00000005','30/04/22','01/05/22','01/05/23',3000);

SELECT * FROM POLIZA_COAR;

COMMIT;

-- Tabla de relacion ACCIDENTE
CREATE TABLE ACCIDENTE_COAR(
   ID_CLIENTE NUMBER(5),
   NUM_SERIE CHAR(8),
   ID_AGENTE NUMBER(5),
   ID_TIPO_SEGURO NUMBER(2),
   FOLIO_POLIZA CHAR(8),
   ID_AJUSTADOR NUMBER(5), 
   ID_TIPO_ACCIDENTE NUMBER(2),
   FOLIO_ACCIDENTE CHAR(8),
   FECHA DATE,
   LUGAR VARCHAR2(150),
   NUM_HERIDOS NUMBER(5) DEFAULT 0,
   CONSTRAINT ACCIDENTE_COAR_PK PRIMARY KEY (ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,FOLIO_POLIZA,ID_AJUSTADOR,ID_TIPO_ACCIDENTE,FOLIO_ACCIDENTE),
   CONSTRAINT POLIZACOAR_ACCI_COAR_FK FOREIGN KEY (ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,FOLIO_POLIZA) 
                                           REFERENCES POLIZA_COAR(ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,FOLIO),
   CONSTRAINT AJUSCOAR_ACCI_COAR_FK FOREIGN KEY (ID_AJUSTADOR) REFERENCES AJUSTADOR_COAR(ID_AJUSTADOR),
   CONSTRAINT TACOAR_ACCI_COAR_FK FOREIGN KEY (ID_TIPO_ACCIDENTE) REFERENCES TIPO_ACCIDENTE_COAR(ID_TIPO_ACCIDENTE)                                       
);

-- Insertar datos en la tabla ACCIDENTE_COAR
INSERT INTO ACCIDENTE_COAR VALUES (1,'00000001',1,1,'00000001',1,1,'00000001','29/04/22','Calle 1',2);
INSERT INTO ACCIDENTE_COAR VALUES (1,'00000001',1,1,'00000001',1,2,'00000002','29/04/22','Calle 2',2);
INSERT INTO ACCIDENTE_COAR VALUES (1,'00000001',1,1,'00000001',1,3,'00000003','29/04/22','Calle 3',2);
INSERT INTO ACCIDENTE_COAR VALUES (1,'00000001',1,1,'00000001',1,4,'00000004','29/04/22','Calle 4',0);
INSERT INTO ACCIDENTE_COAR VALUES (1,'00000001',1,1,'00000001',1,5,'00000005','29/04/22','Calle 5',0);

SELECT * FROM ACCIDENTE_COAR;

COMMIT;

-- Tabla de relacion REPARACION
CREATE TABLE REPARACION_COAR(
   ID_CLIENTE NUMBER(5),
   NUM_SERIE CHAR(8),
   ID_AGENTE NUMBER(5),
   ID_TIPO_SEGURO NUMBER(2),
   FOLIO_POLIZA CHAR(8),
   ID_AJUSTADOR NUMBER(5), 
   ID_TIPO_ACCIDENTE NUMBER(2),
   FOLIO_ACCIDENTE CHAR(8),
   ID_TALLER NUMBER(2),
   ID_REPARACION NUMBER(5),
   FECHA_ENTRADA DATE,
   FECHA_SALIDA DATE,
   DESCRIPCION VARCHAR2(150),
   COSTO NUMBER(8,2), CONSTRAINT REPCOAR_COST_CK CHECK (COSTO>0),
   CONSTRAINT REPARACION_COAR_PK PRIMARY KEY (ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,
            FOLIO_POLIZA,ID_AJUSTADOR,ID_TIPO_ACCIDENTE,FOLIO_ACCIDENTE,ID_TALLER,ID_REPARACION),
   CONSTRAINT ACCICOAR_REPCOAR_FK FOREIGN KEY (ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,
            FOLIO_POLIZA,ID_AJUSTADOR,ID_TIPO_ACCIDENTE,FOLIO_ACCIDENTE) 
                                           REFERENCES ACCIDENTE_COAR(ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,
            FOLIO_POLIZA,ID_AJUSTADOR,ID_TIPO_ACCIDENTE,FOLIO_ACCIDENTE),         
   CONSTRAINT TALLCOAR_REPCOAR_FK FOREIGN KEY (ID_TALLER) REFERENCES TALLER_COAR(ID_TALLER)
);

-- Insertar datos en la tabla REPARACION_COAR
INSERT INTO REPARACION_COAR VALUES (1,'00000001',1,1,'00000001',1,1,'00000001',2,1,'29/04/22','30/04/22','Reparacion 1',5000);
INSERT INTO REPARACION_COAR VALUES (1,'00000001',1,1,'00000001',1,1,'00000001',2,2,'29/04/22','30/04/22','Reparacion 2',5000);
INSERT INTO REPARACION_COAR VALUES (1,'00000001',1,1,'00000001',1,1,'00000001',2,3,'29/04/22','30/04/22','Reparacion 3',2000);
INSERT INTO REPARACION_COAR VALUES (1,'00000001',1,1,'00000001',1,1,'00000001',2,4,'29/04/22','30/04/22','CAMBIO DEL RADIADOR',500);
INSERT INTO REPARACION_COAR VALUES (1,'00000001',1,1,'00000001',1,1,'00000001',2,5,'29/04/22','30/04/22','CAMBIO DE ACEITE',700);

SELECT * FROM REPARACION_COAR;

--Actualizar datos de la REPARACION_COAR
UPDATE REPARACION_COAR SET DESCRIPCION='CAMBIO DEL KIT DE DISTRIBUCION' WHERE 
                                                   ID_CLIENTE=1 AND NUM_SERIE='00000001' AND ID_AGENTE=1 
                                                   AND ID_TIPO_SEGURO=1 AND FOLIO_POLIZA='00000001' 
                                                   AND ID_AJUSTADOR=1 AND ID_TIPO_ACCIDENTE=1 AND 
                                                   FOLIO_ACCIDENTE='00000001' AND ID_TALLER=2 AND ID_REPARACION=1;

UPDATE REPARACION_COAR SET DESCRIPCION='CAMBIAR LAS PASTILLAS DE FRENO', FECHA_ENTRADA='03/05/22', 
                                                   FECHA_SALIDA='10/05/22' WHERE 
                                                   ID_CLIENTE=1 AND NUM_SERIE='00000001' AND ID_AGENTE=1 
                                                   AND ID_TIPO_SEGURO=1 AND FOLIO_POLIZA='00000001' 
                                                   AND ID_AJUSTADOR=1 AND ID_TIPO_ACCIDENTE=1 AND 
                                                   FOLIO_ACCIDENTE='00000001' AND ID_TALLER=2 AND ID_REPARACION=2;

UPDATE REPARACION_COAR SET DESCRIPCION='SUSTITUCION DE LA BOMBA DEL AGUA', FECHA_ENTRADA='11/05/22', 
                                                   FECHA_SALIDA='15/05/22' WHERE 
                                                   ID_CLIENTE=1 AND NUM_SERIE='00000001' AND ID_AGENTE=1 
                                                   AND ID_TIPO_SEGURO=1 AND FOLIO_POLIZA='00000001' 
                                                   AND ID_AJUSTADOR=1 AND ID_TIPO_ACCIDENTE=1 AND 
                                                   FOLIO_ACCIDENTE='00000001' AND ID_TALLER=2 AND ID_REPARACION=3; 

UPDATE REPARACION_COAR SET DESCRIPCION='SUSTITUCION DE LA BOMBA DEL AGUA', FECHA_ENTRADA='12/05/22', 
                                                   FECHA_SALIDA='18/05/22' WHERE 
                                                   ID_CLIENTE=1 AND NUM_SERIE='00000001' AND ID_AGENTE=1 
                                                   AND ID_TIPO_SEGURO=1 AND FOLIO_POLIZA='00000001' 
                                                   AND ID_AJUSTADOR=1 AND ID_TIPO_ACCIDENTE=1 AND 
                                                   FOLIO_ACCIDENTE='00000001' AND ID_TALLER=2 AND ID_REPARACION=4;   

UPDATE REPARACION_COAR SET FECHA_ENTRADA='20/05/22', FECHA_SALIDA='28/05/22', COSTO=1500 WHERE 
                                                   ID_CLIENTE=1 AND NUM_SERIE='00000001' AND ID_AGENTE=1 
                                                   AND ID_TIPO_SEGURO=1 AND FOLIO_POLIZA='00000001' 
                                                   AND ID_AJUSTADOR=1 AND ID_TIPO_ACCIDENTE=1 AND 
                                                   FOLIO_ACCIDENTE='00000001' AND ID_TALLER=2 AND ID_REPARACION=5;                                                                                                                                                   

COMMIT;

-- Tabla PAGO_POLIZA_COAR
CREATE TABLE PAGO_POLIZA_COAR(
   ID_CLIENTE NUMBER(5),
   NUM_SERIE CHAR(8),
   ID_AGENTE NUMBER(5),
   ID_TIPO_SEGURO NUMBER(2),
   FOLIO_POLIZA CHAR(8),
   FOLIO_PAGO NUMBER(5),
   FECHA DATE,
   MONTO NUMBER(8,2) CONSTRAINT PPCOAR_MONTO_NN NOT NULL CONSTRAINT PPCOAR_MONTO_CK CHECK (MONTO>0),
   DESCUENTO NUMBER(8,2) DEFAULT 0 CONSTRAINT PPCOAR_DESCUENTO_NN NOT NULL,
   SUBTOTAL NUMBER(8,2) CONSTRAINT PPCOAR_SUBTOTAL_NN NOT NULL CONSTRAINT PPCOAR_SUBTOTAL_CK CHECK (SUBTOTAL>0),
   CONSTRAINT PPCOAR_PK PRIMARY KEY (FOLIO_PAGO),
   CONSTRAINT PPCOAR_CLI_FK FOREIGN KEY (ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,FOLIO_POLIZA) 
                           REFERENCES POLIZA_COAR(ID_CLIENTE,NUM_SERIE,ID_AGENTE,ID_TIPO_SEGURO,FOLIO)
);

-- Tabla PAGO_POLIZA_COAR
INSERT INTO PAGO_POLIZA_COAR VALUES (1,'00000001',1,1,'00000001',1,'29/04/22',5000,0,5000);
INSERT INTO PAGO_POLIZA_COAR VALUES (1,'00000001',1,1,'00000001',2,'30/04/22',1500,100,1400);
INSERT INTO PAGO_POLIZA_COAR VALUES (1,'00000001',1,1,'00000001',3,'02/05/22',3500,500,3000);
INSERT INTO PAGO_POLIZA_COAR VALUES (1,'00000001',1,1,'00000001',4,'05/05/22',4000,0,4000);
INSERT INTO PAGO_POLIZA_COAR VALUES (1,'00000001',1,1,'00000001',5,'20/05/22',1500,500,1000);

SELECT * FROM PAGO_POLIZA_COAR;

COMMIT;