-- ACTIVIDAD: CAPITULO_08.
-- MATERIA: SISTEMAS DE BASE DE DATOS II.
-- NOMBRE: CRISITAN OMAR ALVARADO RODRIGUEZ.
-- GRUPO: 5"B".

-- Elaborar 3 sentencias con el operador UNION.
SELECT ID_EMPLEADO FROM EMPLEADO_COAR
UNION
SELECT ID_EMPLEADO FROM AGENCIA_EMPLEADO_COAR;

SELECT ID_CLIENTE FROM CLIENTE_COAR
UNION 
SELECT ID_CLIENTE FROM RESERVACION_COAR;

SELECT ID_AGENCIA, ID_EMPLEADO FROM AGENCIA_EMPLEADO_COAR
UNION
SELECT ID_AGENCIA, ID_EMPLEADO FROM RESERVACION_COAR;

-- Elaborar 3 sentencias con el operador UNION ALL.
SELECT ID_AGENCIA, ID_EMPLEADO FROM AGENCIA_EMPLEADO_COAR
UNION ALL
SELECT ID_AGENCIA, ID_EMPLEADO FROM RESERVACION_COAR;

SELECT ID_HOTEL, ID_HABITACION FROM HOTEL_HABITACION_COAR
UNION ALL
SELECT ID_HOTEL, ID_HABITACION FROM RESERVACION_COAR;

SELECT ID_CATEGORIA_HOTEL FROM CATEGORIA_HOTEL_COAR
UNION ALL
SELECT ID_CATEGORIA_HOTEL FROM HOTEL_COAR;

-- Elaborar 3 sentencias con el operador INTERSECT.
SELECT ID_EMPLEADO FROM EMPLEADO_COAR
INTERSECT
SELECT ID_EMPLEADO FROM AGENCIA_EMPLEADO_COAR;

SELECT ID_CLIENTE FROM CLIENTE_COAR
INTERSECT
SELECT ID_CLIENTE FROM RESERVACION_COAR;

SELECT ID_AGENCIA, ID_EMPLEADO FROM AGENCIA_EMPLEADO_COAR
INTERSECT
SELECT ID_AGENCIA, ID_EMPLEADO FROM RESERVACION_COAR;

-- Elaborar 3 sentencias con el operador MINUS.
SELECT ID_EMPLEADO FROM EMPLEADO_COAR
MINUS
SELECT ID_EMPLEADO FROM AGENCIA_EMPLEADO_COAR;

SELECT ID_HOTEL, ID_HABITACION FROM HOTEL_HABITACION_COAR
MINUS
SELECT ID_HOTEL, ID_HABITACION FROM RESERVACION_COAR;

SELECT ID_CLIENTE FROM CLIENTE_COAR
MINUS
SELECT ID_CLIENTE FROM RESERVACION_COAR;
