-- Compa�ia de Telefonos.
-- Practica 02, Actividad 3.

-- TABLE SUBSCRIBER
CREATE TABLE SUBSCRIBER ( 
    NUMBER_CUSTOMER NUMBER(6) CONSTRAINT SUBSCRIBER_PK PRIMARY KEY,
    FRIST_NAME VARCHAR2(35) CONSTRAINT SUB_FRIST_NAME_NN NOT NULL,
    LAST_NAME VARCHAR2(35) CONSTRAINT SUB_LAST_NAME_NN NOT NULL,
    BIRTHDAY DATE CONSTRAINT SUB_BIRTHDAY_NN NOT NULL, 
    ADDRESS VARCHAR2(100) CONSTRAINT SUB_ADDRESS_NN NOT NULL,
    RFC VARCHAR2(13) CONSTRAINT SUB_RFC_NN NOT NULL
);

SELECT * FROM SUBSCRIBER;

-- TABLE OF REFERENCES
CREATE TABLE REFERENCE_SUBSCRIBER (
    NUMBER_REFERENCE NUMBER(6) CONSTRAINT REFERENCE_SUB_PK PRIMARY KEY,
    FRIST_NAME VARCHAR2(35) CONSTRAINT REF_SUB_FRIST_NAME_NN  NOT NULL,
    LAST_NAME VARCHAR2(35) CONSTRAINT REF_SUB_LAST_NAME_NN NOT NULL,
    ADDRESS VARCHAR2(100) CONSTRAINT REF_SUB_ADRESS_NN NOT NULL,
    NUMBER_CUSTOMER NUMBER(6),
    CONSTRAINT SUB_REFERENCE_SUB_FK FOREIGN KEY (NUMBER_CUSTOMER) 
                                    REFERENCES SUBSCRIBER (NUMBER_CUSTOMER)
); 

SELECT * FROM REFERENCE_SUBSCRIBER;

-- TABLE TELEPHONE_ACTIVE
CREATE TABLE TELEPHONE_ACTIVE (
    PHONE_NUMBER NUMBER(10), 
    NUMBER_CUSTOMER NUMBER(6),
    ACTIVATION_DATE DATE CONSTRAINT TEL_ACTIVE_ACT_DATE_NN NOT NULL,
    BRAND VARCHAR2(60) CONSTRAINT TEL_ACTIVE_BRAND_NN NOT NULL,
    ABILITY VARCHAR2(35) CONSTRAINT TEL_ACTIVE_ABILITY_NN NOT NULL,
    MEMORY VARCHAR2(35) CONSTRAINT TEL_ACTIVE_MEMORY_NN NOT NULL,
    CPU VARCHAR2(35) CONSTRAINT TEL_ACTIVE_CPU_NN NOT NULL,
    DISPLEY VARCHAR2(35) CONSTRAINT TEL_ACTIVE_DISPLEY_NN NOT NULL,
    CAMERA VARCHAR2(45) CONSTRAINT TEL_ACTIVE_CAMERA_ NOT NULL,
    SERIAL_NUMBER VARCHAR2(25) CONSTRAINT TEL_ACTIVE_SN_NN NOT NULL,
    PLAN_START_DATE DATE CONSTRAINT TEL_ACTIVE_PSD_NN NOT NULL,
    PLAN_END_DATE DATE CONSTRAINT TEL_ACTIVE_PED_NN NOT NULL,
    PLAN_DURATION VARCHAR2(35) CONSTRAINT TEL_ACTIVE_DP_NN NOT NULL,
    CONSTRAINT SUBSCRIBER_TEL_ACTIVE_PK PRIMARY KEY (PHONE_NUMBER, NUMBER_CUSTOMER),
    CONSTRAINT SUBSCRIBER_TEL_ACTIVE_FK FOREIGN KEY (NUMBER_CUSTOMER)
                                        REFERENCES SUBSCRIBER (NUMBER_CUSTOMER)
);

SELECT * FROM TELEPHONE_ACTIVE;

-- TABLE TELEPHONE_INACTIVE
CREATE TABLE TELEPHONE_INACTIVE (
    PHONE_NUMBER NUMBER(10) CONSTRAINT TELEPHONE_INACTIVE_PK PRIMARY KEY,
    ACTIVATION_DATE DATE CONSTRAINT TELE_INA_ACT_DATE_NN NOT NULL,
    PLAN_START_DATE DATE CONSTRAINT TEL_INA_PSD_NN NOT NULL,
    PLAN_END_DATE DATE CONSTRAINT TEL_INA_PED_NN NOT NULL,
    PLAN_DURATION VARCHAR2(35) CONSTRAINT TEL_INA_DP_NN NOT NULL
);

SELECT * FROM TELEPHONE_INACTIVE;

-- TABLE PHONE_CALL
CREATE TABLE PHONE_CALL (
    PHONE_NUMBER NUMBER(10),
    NUMBER_CUSTOMER NUMBER(6),
    START_TIME DATE CONSTRAINT PHONE_CALL_START_TIME_NN NOT NULL,
    END_TIME DATE CONSTRAINT PHONE_CALL_END_TIME_NN NOT NULL,
    CALL_DURATION_MIN NUMBER(6) CONSTRAINT PHONE_CALL_DUR_MIN_NN NOT NULL,
    CONSTRAINT TEL_ACTIVE_PHONE_CALL_FK FOREIGN KEY (PHONE_NUMBER, NUMBER_CUSTOMER)
                                        REFERENCES TELEPHONE_ACTIVE (PHONE_NUMBER, NUMBER_CUSTOMER)            
);

SELECT * FROM PHONE_CALL;
