-- Practica 3, Actividad 4

CREATE TABLE EMPLOYEE (
    ID_EMPLOYEE NUMBER(5) CONSTRAINT EMPLOYEE_PK PRIMARY KEY,
    FRIST_NAME VARCHAR2(35) CONSTRAINT EMP_FRIST_NAME_NN NOT NULL,
    LAST_NAME VARCHAR2(45) CONSTRAINT EMP_LAST_NAME_NN NOT NULL,
    PHONE VARCHAR2(10) CONSTRAINT EMP_PHONE_NN NOT NULL,
    ADDRESS VARCHAR2(120) CONSTRAINT EMP_ADDRESS_NN NOT NULL,
    LOCATION VARCHAR2(45) CONSTRAINT EMP_LOCATION_NN NOT NULL,
    TURN VARCHAR2(45) CONSTRAINT EMP_TURN_NN NOT NULL
);

SELECT * FROM EMPLOYEE;

CREATE TABLE CLIENT ( 
    ID_CLIENT NUMBER(5) CONSTRAINT CLIENT_PK PRIMARY KEY,
    LOCATION VARCHAR2(45) CONSTRAINT CLI_LOCATION_NN NOT NULL,
    FRIST_NAME VARCHAR2(35) CONSTRAINT CLI_FRIST_NAME_NN NOT NULL,
    LAST_NAME VARCHAR2(45) CONSTRAINT CLI_LAST_NAME_NN NOT NULL,
    PHONE VARCHAR2(10) CONSTRAINT CLI_PHONE_NN NOT NULL,
    ADDRESS VARCHAR2(120) CONSTRAINT CLI_ADDRESS_NN NOT NULL
);

SELECT * FROM CLIENT;

CREATE TABLE SHOES (
    ID_SHOES CHAR(6) CONSTRAINT SHOES_PK PRIMARY KEY,
    PRICE NUMBER(8,2) CONSTRAINT SHOES_PRICE_NN NOT NULL,
    SIZE_SHOE NUMBER(2) CONSTRAINT SHOES_SIZE_NN NOT NULL,
    BRAND VARCHAR2(45) CONSTRAINT SHOES_BRAND_NN NOT NULL
);

SELECT * FROM SHOES;

CREATE TABLE SHOE_TYPE (
    ID_TYPE CHAR(6) CONSTRAINT SHOE_TYPE_PK PRIMARY KEY,
    DESCRIPTION VARCHAR2(100) CONSTRAINT SHOE_TYPE__DES_NN NOT NULL
);

SELECT * FROM SHOE_TYPE;

CREATE TABLE CLASSIFY (
    ID_SHOES CHAR(6),
    ID_TYPE CHAR(6),
    CONSTRAINT SHOES_CLASSIFY_FK FOREIGN KEY (ID_SHOES) REFERENCES SHOES (ID_SHOES),
    CONSTRAINT SHOES_TYPE_CLASS_FK FOREIGN KEY (ID_TYPE) REFERENCES SHOE_TYPE (ID_TYPE)  
);

SELECT * FROM CLASSIFY;

CREATE TABLE SALE (
    PAYMENT_TYPE CHAR(6) CONSTRAINT SALE_PYMENT_T_NN NOT NULL,
    FOLIO_SALE VARCHAR2(10) CONSTRAINT SALE_FOLIO_S_PK PRIMARY KEY,
    ID_EMPLOYEE NUMBER(5),
    ID_CLIENT NUMBER(5),
    ID_SHOES CHAR(6),
    CONSTRAINT SALE_EMPL_FK FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE (ID_EMPLOYEE),
    CONSTRAINT SALE_CLIENT_FK FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID_CLIENT),
    CONSTRAINT SALE_SHOES_FK FOREIGN KEY (ID_SHOES) REFERENCES SHOES (ID_SHOES)
);

SELECT * FROM SALE;
