-- Actividad 02: Hotel.
-- Materia: Sistema de Base de Datos II.
-- Grupo: 5"B".
-- Nombre: Cristian Omar Alvarado Rodriguez.

-- TABLA EMPLEADO_COAR
CREATE TABLE EMPLEADO_COAR (
    ID_EMPLEADO NUMBER(6) CONSTRAINT EMPLEADO_COAR_PK PRIMARY KEY,
    APATERNO VARCHAR2(35) CONSTRAINT EMPLEADO_COAR_APA_NN NOT NULL,
    AMATERNO VARCHAR2(35),
    NOMBRE VARCHAR2(50) CONSTRAINT EMPLEADO_COAR_NOM_NN NOT NULL,
    CORREO VARCHAR2(25) CONSTRAINT EMP_COAR_CORREO_NN NOT NULL CONSTRAINT EMP_COAR_CORREO_UK UNIQUE,
    TELEFONO VARCHAR2(10) CONSTRAINT EMP_COAR_TELEFONO_NN NOT NULL, 
    DIRECCION  VARCHAR2(100) CONSTRAINT EMP_COAR_DIRECCION_NN NOT NULL,
    FECHA_CONTRATACION DATE CONSTRAINT EMPLEADO_COAR_FC_NN NOT NULL,
    SALARIO NUMBER(8,2) CONSTRAINT EMP_COAR_SALARIO_CK CHECK (SALARIO > 0)
);

SELECT * FROM EMPLEADO_COAR;

-- TABLA AGENCIA_COAR
CREATE TABLE AGENCIA_COAR (
    ID_AGENCIA NUMBER(6) CONSTRAINT AGENCIA_COAR_PK PRIMARY KEY,
    NOMBRE VARCHAR2(45) CONSTRAINT AGENCIA_COAR_NOMBRE_NN NOT NULL,
    TELEFONO VARCHAR2(10) CONSTRAINT AGENCIA_COAR_TEL_NN NOT NULL,
    DOMICILIO VARCHAR2(75) CONSTRAINT AGENCIA_COAR_DOMI_NN NOT NULL
);

SELECT * FROM AGENCIA_COAR;

-- TABLA DE RELACION AGENCIA_EMPLEADO_COAR
CREATE TABLE AGENCIA_EMPLEADO_COAR (
    ID_AGENCIA NUMBER(6),
    ID_EMPLEADO NUMBER(6),
    FECHA_ASIGNACION DATE CONSTRAINT AGE_EMPL_COAR_FA_NN NOT NULL,
    CONSTRAINT AGE_EMPL_COAR_PK PRIMARY KEY (ID_AGENCIA, ID_EMPLEADO),
    CONSTRAINT AGE_COAR_AGE_EMPL_COAR_FK FOREIGN KEY (ID_AGENCIA)
                                         REFERENCES AGENCIA_COAR (ID_AGENCIA),
    CONSTRAINT EMPL_COAR_AGE_EMPL_COAR_FK FOREIGN KEY (ID_EMPLEADO)
                                          REFERENCES EMPLEADO_COAR (ID_EMPLEADO)        
);

SELECT * FROM AGENCIA_EMPLEADO_COAR;

-- TABLA CLIENTE_COAR
CREATE TABLE CLIENTE_COAR (
    ID_CLIENTE NUMBER(6) CONSTRAINT CLIENTE_COAR_PK PRIMARY KEY,
    APATERNO VARCHAR2(35) CONSTRAINT CLIENTE_COAR_APA_NN NOT NULL,
    AMATERNO VARCHAR2(35),
    NOMBRE VARCHAR2(50) CONSTRAINT CLIENTE_COAR_NAM_NN NOT NULL,
    SEXO CHAR(1) CONSTRAINT CLIENTE_COAR_SEX_NN NOT NULL CONSTRAINT CLIENTE_COAR_SEX_CK CHECK (SEXO IN ('F','M')),
    EDAD NUMBER(2) CONSTRAINT CLIENTE_COAR_EDAD_NN NOT NULL, 
    TELEFONO VARCHAR2(10) CONSTRAINT CLIENTE_COAR_TEL_NN NOT NULL,
    DOMICILIO VARCHAR2(75) CONSTRAINT CLIENTE_COAR_DOM_NN NOT NULL
);

SELECT * FROM CLIENTE_COAR;

-- TABLA TIPO_HABITACION_COAR
CREATE TABLE TIPO_HABITACION_COAR (
    ID_TIPO_HABITACION NUMBER(4) CONSTRAINT TIPO_HABI_COAR_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(100) CONSTRAINT TIPO_HABI_COAR_DES_NN NOT NULL
);

SELECT * FROM TIPO_HABITACION_COAR;

-- TABLA HABITACION_COAR
CREATE TABLE HABITACION_COAR (
    ID_HABITACION NUMBER(6) CONSTRAINT HABITACION_COAR_PK PRIMARY KEY,
    NOMBRE VARCHAR2(45) CONSTRAINT HABITACION_COAR_NOM_NN NOT NULL,
    ID_TIPO_HABITACION NUMBER(4),
    CONSTRAINT TIPO_HABI_COAR_HABI_COAR_FK FOREIGN KEY (ID_TIPO_HABITACION)
            REFERENCES TIPO_HABITACION_COAR (ID_TIPO_HABITACION) 
);

SELECT * FROM HABITACION_COAR;

-- TABLA CATEGORIA_HOTEL_COAR
CREATE TABLE CATEGORIA_HOTEL_COAR (
    ID_CATEGORIA_HOTEL NUMBER(4) CONSTRAINT CATEGORIA_HOTEL_COAR_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(55) CONSTRAINT CAT_HOTEL_COAR_DES_NN NOT NULL,
    IVA NUMBER(2) CONSTRAINT CAT_HOTEL_IVA_NN NOT NULL
);

SELECT * FROM CATEGORIA_HOTEL_COAR;

-- TABLA HOTEL_COAR
CREATE TABLE HOTEL_COAR (
    ID_HOTEL NUMBER(6) CONSTRAINT HOTEL_COAR_PK PRIMARY KEY,
    NOMBRE VARCHAR2(75) CONSTRAINT HOTEL_COAR_NAM_NN NOT NULL,
    FECHA_CONSTRUCCION DATE CONSTRAINT HOTEL_COAR_FECHA_CONS_NN NOT NULL,
    TELEFONO VARCHAR2(10) CONSTRAINT HOTEL_COAR_TEL_NN NOT NULL,
    DOMICILIO VARCHAR2(75) CONSTRAINT HOTEL_COAR_DOM_NN NOT NULL,
    ID_CATEGORIA_HOTEL NUMBER(4),
    CONSTRAINT CAT_H_COAR_H_COAR_FK FOREIGN KEY (ID_CATEGORIA_HOTEL)
               REFERENCES CATEGORIA_HOTEL_COAR (ID_CATEGORIA_HOTEL) 
);

SELECT * FROM HOTEL_COAR;

-- TABLA DE RELACION HOTEL_HABITACION_COAR
CREATE TABLE HOTEL_HABITACION_COAR (
    ID_HOTEL NUMBER(6),
    ID_HABITACION NUMBER(6),
    CANTIDAD NUMBER(6) CONSTRAINT HOT_HAB_COAR_CAN_NN NOT NULL,
    CONSTRAINT HOTEL_HAB_COAR_PK PRIMARY KEY (ID_HOTEL, ID_HABITACION),
    CONSTRAINT HOT_COAR_HOT_HAB_COAR_FK FOREIGN KEY (ID_HOTEL) 
            REFERENCES HOTEL_COAR(ID_HOTEL),
    CONSTRAINT HABI_COAR_HOT_HAB_COAR_FK FOREIGN KEY (ID_HABITACION)
            REFERENCES HABITACION_COAR(ID_HABITACION)
);

SELECT * FROM HOTEL_HABITACION_COAR;

-- TABLA DE RELACION RESERVACION_COAR
CREATE TABLE RESERVACION_COAR (
    ID_CLIENTE NUMBER(6),
    ID_AGENCIA NUMBER(6),
    ID_EMPLEADO NUMBER(6),
    ID_HOTEL NUMBER(6),
    ID_HABITACION NUMBER(6),
    FOLIO_RESERVACION CHAR(8) CONSTRAINT RESERVACION_COAR_PK PRIMARY KEY,
    FECHA_INICIO DATE CONSTRAINT RESE_COAR_FECHA_INI_NN NOT NULL,
    FECHA_FIN DATE CONSTRAINT RESE_COAR_FECHA_FIN_NN NOT NULL,
    PRECIO NUMBER(8,2) CONSTRAINT RESE_COAR_PRECIO_NN NOT NULL,
    DESCUENTO NUMBER(6,2),
    SUBTOTAL NUMBER(8,2) CONSTRAINT RES_COAR_SUBT_NN NOT NULL,
    CONSTRAINT CLI_COAR_HOT_RES_COAR_FK FOREIGN KEY (ID_CLIENTE) 
                                       REFERENCES CLIENTE_COAR (ID_CLIENTE),
    CONSTRAINT AGE_EMPL_COAR_RES_COAR_FK FOREIGN KEY (ID_AGENCIA, ID_EMPLEADO)
                                       REFERENCES AGENCIA_EMPLEADO_COAR (ID_AGENCIA, ID_EMPLEADO),
    CONSTRAINT HOT_HABI_COAR_RES_COAR_FK FOREIGN KEY (ID_HOTEL, ID_HABITACION)
                                       REFERENCES HOTEL_HABITACION_COAR (ID_HOTEL, ID_HABITACION)                                             
);

SELECT * FROM RESERVACION_COAR;

-- SECUENCIAS PARA LAS LLAVES PRIMARIAS DE LAS TABLAS
CREATE SEQUENCE EMP_COAR_ID_EMP_SEQ
                INCREMENT BY 10
                START WITH 30
                MAXVALUE 1000;

CREATE SEQUENCE AGE_COAR_ID_AGE_SEQ
                INCREMENT BY 1
                START WITH 100
                MAXVALUE 500;

CREATE SEQUENCE CLI_COAR_ID_CLI_SEQ
                INCREMENT BY 5
                START WITH 5
                MAXVALUE 1000;

CREATE SEQUENCE T_HABI_COAR_ID_THABI_SEQ
                INCREMENT BY 1
                START WITH 100
                MAXVALUE 100;

CREATE SEQUENCE HABI_COAR_ID_HABI_SEQ 
                INCREMENT BY 1
                START WITH 1
                MAXVALUE 1000;

CREATE SEQUENCE CAT_HOT_COAR_ID_CAT_HOT_SEQ
                INCREMENT BY 10
                START WITH 15
                MAXVALUE 200;

CREATE SEQUENCE HOT_COAR_ID_HOT_SEQ
                INCREMENT BY 10
                START WITH 50
                MAXVALUE 1000;

-- SINONIMOS PARA LAS TABLAS
CREATE SYNONYM E_COAR FOR EMPLEADO_COAR;
CREATE SYNONYM A_COAR FOR AGENCIA_COAR;
CREATE SYNONYM AE_COAR FOR AGENCIA_EMPLEADO_COAR;
CREATE SYNONYM C_COAR FOR CLIENTE_COAR;
CREATE SYNONYM T_HA_COAR FOR TIPO_HABITACION_COAR;
CREATE SYNONYM HA_COAR FOR HABITACION_COAR;
CREATE SYNONYM C_HO_COAR FOR CATEGORIA_HOTEL_COAR;
CREATE SYNONYM HO_COAR FOR HOTEL_COAR;
CREATE SYNONYM HO_HA_COAR FOR HOTEL_HABITACION_COAR;
CREATE SYNONYM R_COAR FOR RESERVACION_COAR;

-- INDICES PARA LAS TABLAS
CREATE INDEX EMP_COAR_NOM_APA_AMA_IDX ON E_COAR(NOMBRE, APATERNO, AMATERNO);
CREATE INDEX EMP_COAR_FECHA_CON_IDX ON E_COAR(FECHA_CONTRATACION);
CREATE INDEX EMP_COAR_SALARIO_IDX ON E_COAR(SALARIO);
CREATE INDEX AGE_COAR_NOMBRE_IDX ON A_COAR(NOMBRE);
CREATE INDEX CLI_COAR_NOM_APA_AMA_IDX ON C_COAR(NOMBRE, APATERNO, AMATERNO);
CREATE INDEX HAB_COAR_NOMBRE_IDX ON HA_COAR(NOMBRE);
CREATE INDEX HAB_COAR_ID_TIPO_HA_IDX ON HA_COAR(ID_TIPO_HABITACION);
CREATE INDEX CAT_HOT_COAR_DES_IDX ON C_HO_COAR(DESCRIPCION);
CREATE INDEX HOT_COAR_NOMBRE_IDX ON HO_COAR(NOMBRE);
CREATE INDEX HOT_COAR_ID_CAT_HOT_IDX ON HO_COAR(ID_CATEGORIA_HOTEL);
CREATE INDEX RES_COAR_ID_CLI_IDX ON R_COAR(ID_CLIENTE);
CREATE INDEX RES_COAR_ID_AGE_IDX ON R_COAR(ID_AGENCIA);
CREATE INDEX RES_COAR_ID_EMP_IDX ON R_COAR(ID_EMPLEADO);
CREATE INDEX RES_COAR_ID_HOT_IDX ON R_COAR(ID_HOTEL);
CREATE INDEX RES_COAR_ID_HAB_IDX ON R_COAR(ID_HABITACION);

-- ########### ACTIVIDA DEL CAPITULO 9 #########
-- Insertar 5 registros a cada tabla haciendo uso de las secuencias.

-- INSERTAR DATOS EN LA TABLA EMPLEADO_COAR:
INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'ALVARADO', 'RODRIGUEZ', 
            'CRISTIAN', 'CRIS@GMAIL.COM', '4927859842', 'ZACATECAS NUM 56', 
            TO_DATE('SEP 5, 2022','MON DD, YYYY'), 3000);

INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'GUZMAN', 'LOERA', 
            'JOAQUIN', 'JOAQ@GMAIL.COM', '4924657313', 'La Tuna, Badiraguato, Sinaloa', 
            TO_DATE('SEP 7, 2022','MON DD, YYYY'), 5000);

INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'LOPEZ', 'PEREZ', 
            'NANCY', 'NAN@GMAIL.COM', '8426753489', 'GUADALUPE, ZAC NUM 21', 
            TO_DATE('SEP 10, 2022','MON DD, YYYY'), 2300);

INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'GARCIA', 'TORRES', 
            'JUAN', 'JUAN@GMAIL.COM', '4926758943', 'ZACATECAS NUM 87', 
            TO_DATE('SEP 10, 2022','MON DD, YYYY'), 2600);

INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'DIAZ', 'FLORES', 
            'ANA', 'ANA@GMAIL.COM', '4929346123', 'ZACATECAS NUM 73', 
            TO_DATE('SEP 12, 2022','MON DD, YYYY'), 3000);

INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'PEREZ', 'OLVERA', 
            'JOSE', 'JOSE@GMAIL.COM', '4928294794', 'ZACATECAS NUM 701', 
            TO_DATE('SEP 15, 2022','MON DD, YYYY'), 1500);

SELECT * FROM E_COAR;

-- INSERTAR DATOS EN LA TABLA AGENCIA_COAR:
INSERT INTO A_COAR VALUES (AGE_COAR_ID_AGE_SEQ.NEXTVAL, 'TRIVAGO', 
            '9179069307', 'TEPITO, CDMX, NUM 45'); 

INSERT INTO A_COAR VALUES (AGE_COAR_ID_AGE_SEQ.NEXTVAL, 'HARD ROCK', 
            '8002720216', 'Cabo San Lucas, Baja California Sur');

INSERT INTO A_COAR VALUES (AGE_COAR_ID_AGE_SEQ.NEXTVAL, 'EXPEDIA', 
            '7856489321', 'Seattle, Washington, Estados Unidos');

INSERT INTO A_COAR VALUES (AGE_COAR_ID_AGE_SEQ.NEXTVAL, 'HOTELBEDS', 
            '4567394727', 'Palma de Mallorca, España');

INSERT INTO A_COAR VALUES (AGE_COAR_ID_AGE_SEQ.NEXTVAL, 'WIHP HOTELS', 
            '4925673291', 'ZACATECAS, NUM 123');

INSERT INTO A_COAR VALUES (AGE_COAR_ID_AGE_SEQ.NEXTVAL, 'MI AGENCIA COOL', 
            '4926898092', 'ZACATECAS, NUM 09');

SELECT * FROM A_COAR;

-- INSERTAR DATOS EN LA TABLA AGENCIA_EMPLEADO_COAR:
SELECT * FROM E_COAR;
SELECT * FROM A_COAR;

INSERT INTO AE_COAR VALUES (103, 50, TO_DATE('AGO 05, 2022','MON DD, YYYY'));
INSERT INTO AE_COAR VALUES (101, 30, TO_DATE('AGO 06, 2022','MON DD, YYYY'));
INSERT INTO AE_COAR VALUES (104, 40, TO_DATE('AGO 05, 2022','MON DD, YYYY'));
INSERT INTO AE_COAR VALUES (104, 70, TO_DATE('AGO 05, 2022','MON DD, YYYY'));
INSERT INTO AE_COAR VALUES (102, 60, TO_DATE('AGO 17, 2022','MON DD, YYYY'));

SELECT * FROM AE_COAR;

-- INSERTAR DATOS EN LA TABLA CLIENTE_COAR:
INSERT INTO C_COAR VALUES (CLI_COAR_ID_CLI_SEQ.NEXTVAL, 'RAMIREZ', 'HERNANDEZ',
            'LUIS', 'M', 25, '4927402032', 'ZACATECAS, NUM 15');

INSERT INTO C_COAR VALUES (CLI_COAR_ID_CLI_SEQ.NEXTVAL, 'GUTIERREZ', 'SANCHEZ', 
            'VANESA', 'F', 29, '4924678531', 'ZACATECAS, NUM 90');

INSERT INTO C_COAR VALUES (CLI_COAR_ID_CLI_SEQ.NEXTVAL, 'VAZQUEZ', 'ZORRILLA',
            'MARIO', 'M', 36, '4924528238', 'ZACATECAS, NUM 32');

INSERT INTO C_COAR VALUES (CLI_COAR_ID_CLI_SEQ.NEXTVAL, 'ROMO', 'PEREZ',
            'OMAR', 'M', 21, '4929044563', 'ZACATECAS, NUM 345');

INSERT INTO C_COAR VALUES (CLI_COAR_ID_CLI_SEQ.NEXTVAL, 'ALVAREZ', 'MARTINEZ',
            'FERNANDA', 'F', 32, '4925673458', 'ZACATECAS, NUM 56');

INSERT INTO C_COAR VALUES (CLI_COAR_ID_CLI_SEQ.NEXTVAL, 'ZAPATA', 'GUTIERREZ',
            'MIGUEL', 'M', 22, '4926892759', 'ZACATECAS, NUM 15');

SELECT * FROM C_COAR; 

-- INSERTAR DATOS EN LA TABLA TIPO_HABITACION_COAR:
ALTER SEQUENCE T_HABI_COAR_ID_THABI_SEQ
                MAXVALUE 500;

INSERT INTO T_HA_COAR VALUES (T_HABI_COAR_ID_THABI_SEQ.NEXTVAL, 'SUITE');
INSERT INTO T_HA_COAR VALUES (T_HABI_COAR_ID_THABI_SEQ.NEXTVAL, 'JUNIOR SUITE');
INSERT INTO T_HA_COAR VALUES (T_HABI_COAR_ID_THABI_SEQ.NEXTVAL, 'GRAN SUITE');
INSERT INTO T_HA_COAR VALUES (T_HABI_COAR_ID_THABI_SEQ.NEXTVAL, 'INDIVIDUAL');
INSERT INTO T_HA_COAR VALUES (T_HABI_COAR_ID_THABI_SEQ.NEXTVAL, 'DOBLE');

SELECT * FROM T_HA_COAR;

-- INSERTAR DATOS EN LA TABLA HABITACION_COAR:
INSERT INTO HA_COAR VALUES (HABI_COAR_ID_HABI_SEQ.NEXTVAL, 'SENCILLA', 104);
INSERT INTO HA_COAR VALUES (HABI_COAR_ID_HABI_SEQ.NEXTVAL, 'SENCILLA', 105);
INSERT INTO HA_COAR VALUES (HABI_COAR_ID_HABI_SEQ.NEXTVAL, 'QUAD', 101);
INSERT INTO HA_COAR VALUES (HABI_COAR_ID_HABI_SEQ.NEXTVAL, 'KING', 102);
INSERT INTO HA_COAR VALUES (HABI_COAR_ID_HABI_SEQ.NEXTVAL, 'TWIN', 103);

SELECT * FROM HA_COAR;

-- INSERTAR DATOS EN LA TABLA CATEGORIA_HOTEL_COAR:
ALTER TABLE CATEGORIA_HOTEL_COAR MODIFY IVA NUMBER(4,2);

INSERT INTO C_HO_COAR VALUES (CAT_HOT_COAR_ID_CAT_HOT_SEQ.NEXTVAL, '1 ESTRELLA', 0.16);
INSERT INTO C_HO_COAR VALUES (CAT_HOT_COAR_ID_CAT_HOT_SEQ.NEXTVAL, '2 ESTRELLAS', 0.12);
INSERT INTO C_HO_COAR VALUES (CAT_HOT_COAR_ID_CAT_HOT_SEQ.NEXTVAL, '3 ESTRELLAS', 0.10);
INSERT INTO C_HO_COAR VALUES (CAT_HOT_COAR_ID_CAT_HOT_SEQ.NEXTVAL, '4 ESTRELLAS', 0.15);
INSERT INTO C_HO_COAR VALUES (CAT_HOT_COAR_ID_CAT_HOT_SEQ.NEXTVAL, '5 ESTRELLAS', 0.16);

SELECT * FROM C_HO_COAR;

-- INSERTAR DATOS EN LA TABLA HOTEL_COAR:
INSERT INTO HO_COAR VALUES (HOT_COAR_ID_HOT_SEQ.NEXTVAL, 'HOTEL DON MIGUEL', '20/03/1990',
            '4925329032', 'ZACATECAS NUM 65', 45);

INSERT INTO HO_COAR VALUES (HOT_COAR_ID_HOT_SEQ.NEXTVAL, 'HOTEL HACIENDA BARUK', '12/07/1992',
            '4927584924', 'ZACATECAS NUM 20', 35);

INSERT INTO HO_COAR VALUES (HOT_COAR_ID_HOT_SEQ.NEXTVAL, 'CITY EXPRESS ZAC', '25/12/2002',
            '4926567281', 'ZACATECAS NUM 23', 55);

INSERT INTO HO_COAR VALUES (HOT_COAR_ID_HOT_SEQ.NEXTVAL, 'HOTEL RIU EMERALD BAY', '10/04/2009',
            '6699897900', 'MAZATLAN, SINALOA, MX', 45); 

INSERT INTO HO_COAR VALUES (HOT_COAR_ID_HOT_SEQ.NEXTVAL, 'HOTEL MARIA CONCHITA', '27/06/1993',
            '4924786854', 'ZACATECAS NUM 72', 25);                               

SELECT * FROM HO_COAR;

-- INSERTAR DATOS EN LA TABLA HOTEL_HABITACION_COAR:
SELECT * FROM HABITACION_COAR;
SELECT * FROM HOTEL_COAR;

INSERT INTO HOTEL_HABITACION_COAR VALUES (50, 3, 20);
INSERT INTO HOTEL_HABITACION_COAR VALUES (60, 1, 70);
INSERT INTO HOTEL_HABITACION_COAR VALUES (80, 4, 80);
INSERT INTO HOTEL_HABITACION_COAR VALUES (250, 1, 10);
INSERT INTO HOTEL_HABITACION_COAR VALUES (260, 5, 35);

SELECT * FROM HOTEL_HABITACION_COAR;

-- INSERTAR DATOS EN LA TABLA RESERVACION_COAR:
SELECT * FROM C_COAR;
SELECT * FROM AE_COAR;
SELECT * FROM HO_HA_COAR;

INSERT INTO R_COAR VALUES (15, 104, 40, 60, 1, '00000001', '05/09/2022', 
                        '10/09/2022', 3500, 0, 3560);  

INSERT INTO R_COAR VALUES (5, 101, 30, 260, 5, '00000002', '06/09/2022', 
                        '11/09/2022', 4000, 100, 3900);  

INSERT INTO R_COAR VALUES (25, 104, 40, 80, 4, '00000003', '10/09/2022', 
                        '13/09/2022', 3000, 0, 3100);  

INSERT INTO R_COAR VALUES (10, 103, 50, 250, 1, '00000004', '05/09/2022', 
                        '10/09/2022', 3500, 0, 3560);  

INSERT INTO R_COAR VALUES (20, 104, 70, 60, 1, '00000005', '12/09/2022', 
                        '17/09/2022', 5500, 200, 5300);  

INSERT INTO R_COAR VALUES (15, 102, 60, 260, 5, '00000006', '13/09/2022', 
                        '15/09/2022', 7000, 0, 7000);  

INSERT INTO R_COAR VALUES (25, 104, 70, 50, 3, '00000007', '14/09/2022', 
                        '22/09/2022', 6000, 0, 6100);  


SELECT * FROM R_COAR;

COMMIT;

-- ACTUALIZAR 5 REGISTROS
SELECT * FROM C_COAR;
SELECT * FROM E_COAR;
SELECT * FROM R_COAR;

UPDATE C_COAR SET EDAD = 50 WHERE ID_CLIENTE = 20;
UPDATE C_COAR SET TELEFONO = '4920289453' WHERE ID_CLIENTE = 10;
UPDATE E_COAR SET SALARIO = 2800 WHERE ID_EMPLEADO = 60;

UPDATE R_COAR SET FECHA_INICIO = '16/09/2022', FECHA_FIN = '21/09/2022' 
              WHERE FOLIO_RESERVACION = '00000005';

UPDATE R_COAR SET DESCUENTO = 500, SUBTOTAL = 2500 WHERE FOLIO_RESERVACION = '00000003'; 

-- ELIMINAR 5 REGISTROS.
SELECT * FROM E_COAR;
SELECT * FROM A_COAR;
SELECT * FROM C_COAR;
SELECT * FROM R_COAR;

DELETE FROM E_COAR WHERE ID_EMPLEADO = 230;
DELETE FROM A_COAR WHERE ID_AGENCIA = 120;
DELETE FROM C_COAR WHERE ID_CLIENTE = 105;
DELETE FROM R_COAR WHERE FOLIO_RESERVACION = '00000006';
DELETE FROM R_COAR WHERE FOLIO_RESERVACION = '00000007';