
-- Descripciones de las tablas
DESC REGIONS;
DESC COUNTRIES;
DESC LOCATIONS;
DESC DEPARTMENTS;
DESC JOBS;
DESC EMPLOYEES;
DESC JOB_HISTORY;

SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;
