-- RH_COAR.
-- NOMBRE: CRISTIAN OMAR ALVARADO RODRIGUEZ.
-- MATERIA: SISTEMAS DE BASE DE DATOS II.
-- GRUPO: 5 "B".

-- TABLA REGIONES
CREATE TABLE REGION_COAR (
    ID_REGION NUMBER CONSTRAINT REGION_COAR_PK PRIMARY KEY,
    NOMBRE_REGION VARCHAR2(25)    
);

SELECT * FROM REGION_COAR;

-- TABLE PAIS
CREATE TABLE PAIS_COAR (
    ID_PAIS CHAR(2) CONSTRAINT PAIS_COAR_PK PRIMARY KEY,
    NOMBRE_PAIS VARCHAR2(40),
    ID_REGION NUMBER,
    CONSTRAINT REGION_COAR_PAIS_COAR_FK FOREIGN KEY (ID_REGION) 
                                    REFERENCES REGION_COAR (ID_REGION)
);

SELECT * FROM PAIS_COAR;
 
-- Tabla UBICACION_COAR
CREATE TABLE UBICACION_COAR (
    ID_UBICACION NUMBER(4) CONSTRAINT UBICACIONES_COAR_PK PRIMARY KEY,
    DIRECCION VARCHAR2(40),
    CODIGO_POSTAL VARCHAR2(12),
    CIUDAD VARCHAR2(30) CONSTRAINT UBI_COAR_CIUDAD NOT NULL,
    PROVINCIA_ESTADO VARCHAR2(25),
    ID_PAIS CHAR(2),
    CONSTRAINT PAIS_COAR_UBI_COAR_FK FOREIGN KEY (ID_PAIS) 
                                    REFERENCES PAIS_COAR(ID_PAIS)
);

SELECT * FROM UBICACION_COAR;

-- TABLA DEPARTAMENTO_COAR
CREATE TABLE DEPARTAMENTO_COAR (
    ID_DEPARTAMENTO NUMBER(4) CONSTRAINT DEPARTAMENTO_COAR PRIMARY KEY,
    DEPARTAMENTO_NOMBRE VARCHAR2(30) CONSTRAINT DEPA_COAR_DEPA_NOM_NN NOT NULL,
    ID_JEFE NUMBER(6),
    ID_UBICACION NUMBER(4),
    CONSTRAINT UBI_COAR_DEPA_COAR_FK FOREIGN KEY (ID_UBICACION) 
                                    REFERENCES UBICACION_COAR (ID_UBICACION)
);

SELECT * FROM DEPARTAMENTO_COAR;

-- TABLA TRABAJO_COAR
CREATE TABLE TRABAJO_COAR (
    ID_TRABAJO VARCHAR2(10) CONSTRAINT TRABAJO_COAR_PK PRIMARY KEY,
    TITULO_TRABAJO VARCHAR2(35) CONSTRAINT TRABAJO_COAR_TT_NN NOT NULL,
    MIN_SALARIO NUMBER(6),
    MAX_SALARIO NUMBER(6)
);

SELECT * FROM TRABAJO_COAR;

-- TABLA EMPLEADO_COAR
CREATE TABLE EMPLEADO_COAR (
    ID_EMPLEADO NUMBER(6) CONSTRAINT EMPLEADO_COAR_PK PRIMARY KEY,
    APELLIDO_EMPLEADO VARCHAR2(20),
    NOMBRE_EMPLEADO VARCHAR2(20) CONSTRAINT EMP_COAR_NOMBRE_NN NOT NULL,
    CORREO VARCHAR2(25) CONSTRAINT EMP_COAR_CORREO_NN NOT NULL CONSTRAINT EMP_COAR_CORREO_UK UNIQUE,
    TELEFONO VARCHAR2(20),
    FECHA_CONTRATACION DATE CONSTRAINT EMP_COAR_FC_NN NOT NULL,
    ID_TRABAJO VARCHAR2(10),
    SALARIO NUMBER(8,2) CONSTRAINT EMP_COAR_SALARIO_CK CHECK (SALARIO > 0),
    COMICION_PCT NUMBER(2,2),
    ID_JEFE NUMBER(6),
    ID_DEPARTAMENTO NUMBER(6),
    CONSTRAINT DEP_COAR_EMP_COAR_FK FOREIGN KEY (ID_DEPARTAMENTO) 
                                    REFERENCES DEPARTAMENTO_COAR (ID_DEPARTAMENTO),
    CONSTRAINT TRABAJO_COAR_EMP_COAR_FK FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO_COAR (ID_TRABAJO),
    CONSTRAINT JEFE_EMP_COAR_FK FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADO_COAR (ID_EMPLEADO)                                
);

SELECT * FROM EMPLEADO_COAR;

-- TABLA HISTORIAL DE TRABAJO
CREATE TABLE HISTORIAL_TAB_COAR (
    ID_EMPLEADO NUMBER(6),
    FECHA_INICIO DATE CONSTRAINT HIS_TAB_COAR_FI_NN NOT NULL,
    FECHA_FIN DATE CONSTRAINT HIS_TAB_COAR_FF_NN NOT NULL,
    ID_TRABAJO VARCHAR2(10),
    ID_DEPARTAMENTO NUMBER(4),
    CONSTRAINT HIS_TAB_PK PRIMARY KEY (ID_EMPLEADO, FECHA_INICIO),
    CONSTRAINT EMP_COAR_HTAB_COAR_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO_COAR (ID_EMPLEADO),
    CONSTRAINT DEP_COAR_HTAB_COAR_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO_COAR(ID_DEPARTAMENTO),
    CONSTRAINT TAB_COAR_HTAB_COAR FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO_COAR(ID_TRABAJO)
);

SELECT * FROM HISTORIAL_TAB_COAR;

-- LLAVE FORANEA PARA LA TABLA DEPARTAMENTO_COAR
ALTER TABLE DEPARTAMENTO_COAR ADD CONSTRAINT
                            EMP_COAR_DEP_COAR_FK FOREIGN KEY (ID_JEFE) 
                            REFERENCES EMPLEADO_COAR (ID_EMPLEADO);

SELECT * FROM DEPARTAMENTO_COAR;

-- SECUENCIAS PARA LAS TABLAS
CREATE SEQUENCE REG_COAR_REG_ID_SEQ
       INCREMENT BY 1
       START WITH 1;

CREATE SEQUENCE UBI_COAR_UBI_ID_SEQ
        INCREMENT BY 100
        START WITH 1000;

CREATE SEQUENCE DEP_COAR_DEP_ID_SEQ
        INCREMENT BY 2;
        START WITH 10;

CREATE SEQUENCE EMP_COAR_EMP_ID_SEQ
        INCREMENT BY 1
        START WITH 100;

-- SINONIMOS PARA LAS TABLAS
CREATE SYNONYM R_COAR FOR REGION_COAR;
CREATE SYNONYM P_COAR FOR PAIS_COAR;
CREATE SYNONYM U_COAR FOR UBICACION_COAR;
CREATE SYNONYM D_COAR FOR DEPARTAMENTO_COAR;
CREATE SYNONYM T_COAR FOR TRABAJO_COAR;
CREATE SYNONYM E_COAR FOR EMPLEADO_COAR;
CREATE SYNONYM HT_COAR FOR HISTORIAL_TAB_COAR;

-- INDICES PARA LAS COLUMNAS DE LAS TABLAS
CREATE INDEX PAIS_COAR_NOM_IDX ON P_COAR(NOMBRE_PAIS);
CREATE INDEX PAIS_COAR_ID_REGION_IDX ON P_COAR(ID_REGION);
CREATE INDEX UBI_COAR_CIUDAD_IDX ON U_COAR(CIUDAD);
CREATE INDEX UBI_COAR_PRO_ESTADO_IDX ON U_COAR(PROVINCIA_ESTADO);
CREATE INDEX UBI_COAR_ID_PAIS_IDX ON U_COAR(ID_PAIS);
CREATE INDEX DEP_COAR_DEP_NOMB_IDX ON D_COAR(DEPARTAMENTO_NOMBRE);
CREATE INDEX DEP_COAR_DEP_ID_JEFE_IDX ON D_COAR(ID_JEFE);
CREATE INDEX DEP_COAR_DEP_ID_UBI_IDX ON D_COAR(ID_UBICACION);
CREATE INDEX TRA_COAR_TITULO_TAB_IDX ON T_COAR(TITULO_TRABAJO);
CREATE INDEX EMP_COAR_NOM_APE_IDK ON E_COAR(NOMBRE_EMPLEADO, APELLIDO_EMPLEADO);
CREATE INDEX EMP_COAR_ID_TRABAJO_IDX ON E_COAR(ID_TRABAJO);
CREATE INDEX EMP_COAR_ID_JEFE_IDX ON E_COAR(ID_JEFE);
CREATE INDEX EMP_COAR_ID_DEPA_IDX ON E_COAR(ID_DEPARTAMENTO);
CREATE INDEX HIS_TAB_COAR_ID_TAB_IDX ON HT_COAR(ID_TRABAJO);
CREATE INDEX HIS_TAB_COAR_ID_DEP_IDX ON HT_COAR(ID_DEPARTAMENTO);

-- ########### ACTIVIDA DEL CAPITULO 9 #########

-- COPIAR DATOS DEL ESQUEMA DE HR AL ESQUEMA RH_COAR.
INSERT INTO R_COAR SELECT * FROM HR.REGIONS;

INSERT INTO P_COAR SELECT * FROM HR.COUNTRIES;

INSERT INTO U_COAR SELECT * FROM HR.LOCATIONS; 

ALTER TABLE DEPARTAMENTO_COAR DROP CONSTRAINT EMP_COAR_DEP_COAR_FK;
INSERT INTO D_COAR SELECT * FROM HR.DEPARTMENTS;

INSERT INTO T_COAR SELECT * FROM HR.JOBS;

INSERT INTO E_COAR SELECT * FROM HR.EMPLOYEES;

-- LLAVE FORANEA PARA LA TABLA DEPARTAMENTO_COAR
ALTER TABLE DEPARTAMENTO_COAR ADD CONSTRAINT
                            EMP_COAR_DEP_COAR_FK FOREIGN KEY (ID_JEFE) 
                            REFERENCES EMPLEADO_COAR (ID_EMPLEADO);

INSERT INTO HT_COAR SELECT * FROM HR.JOB_HISTORY;                            

COMMIT;

-- Insertar 5 registros a cada tabla de RH haciendo 
-- uso de las secuencias elaboradas.

-- BORRAR LA SEQUENCIA DE EMPLEADO_COAR
DROP SEQUENCE EMP_COAR_EMP_ID_SEQ;

-- CREAR LA SEQUENCIA DE EMPLEADO_COAR
CREATE SEQUENCE EMP_COAR_EMP_ID_SEQ
        INCREMENT BY 1
        START WITH 207;

INSERT INTO E_COAR VALUES (EMP_COAR_EMP_ID_SEQ.NEXTVAL, 'Rodriguez', 'Cristian',
               'RCRISTIAN', '492.674.2139', '10/09/2022', 'IT_PROG', 5200, NULL, 103, 60);

INSERT INTO E_COAR VALUES (EMP_COAR_EMP_ID_SEQ.NEXTVAL, 'Guzman', 'Joaquin',
               'Gjoaquin', '492.784.1357', '12/09/2022', 'PU_CLERK', 4500, NULL, 114, 30);

INSERT INTO T_COAR VALUES ('EM_LIMP', 'Empleado de limpieza', 2000, 3500);
INSERT INTO T_COAR VALUES ('RE_INTER', 'Relaciones Internacionales', 5000, 12000);

INSERT INTO P_COAR VALUES ('PE', 'PERU', 2);
INSERT INTO P_COAR VALUES ('UC', 'Ucrania', 1);

SELECT * FROM E_COAR;
SELECT * FROM T_COAR;
SELECT * FROM P_COAR;

COMMIT;

-- Ejecutar 5 sentencias UPDATE para modificar datos.
UPDATE E_COAR SET SALARIO = 13500 WHERE ID_EMPLEADO = 108;

UPDATE E_COAR SET COMICION_PCT = 0.17 WHERE ID_EMPLEADO = 155;

UPDATE E_COAR SET ID_TRABAJO = 'IT_PROG', ID_JEFE = 102, ID_DEPARTAMENTO = 60, 
SALARIO = 8000 WHERE ID_EMPLEADO = 115;

UPDATE HT_COAR SET ID_TRABAJO = 'IT_PROG', ID_DEPARTAMENTO = 60
WHERE ID_EMPLEADO = 114 AND FECHA_INICIO = '24/03/06';

SELECT * FROM HT_COAR;

UPDATE T_COAR SET MIN_SALARIO = 9000, MAX_SALARIO = 18000 WHERE ID_TRABAJO = 'FI_MGR';

SELECT * FROM T_COAR;

-- Ejecutar 5 sentencias DELETE para eliminar datos
DELETE FROM P_COAR WHERE ID_PAIS = 'PE';
SELECT * FROM P_COAR;

DELETE FROM E_COAR WHERE ID_EMPLEADO = 131;
SELECT * FROM E_COAR;

DELETE FROM P_COAR WHERE ID_PAIS = 'EG';
SELECT * FROM P_COAR;

DELETE FROM U_COAR WHERE ID_UBICACION = 3000;
SELECT * FROM U_COAR;

DELETE FROM E_COAR WHERE ID_EMPLEADO = 178;
SELECT * FROM E_COAR;
