-- ####### ESCENARIOS PARA EL ESQUEMA RH_COAR ########
-- USUARIO 01: RH_COAR.

-- ESCENARIO 01:
SELECT * FROM EMPLEADO_COAR;
UPDATE EMPLEADO_COAR SET SALARIO = 4000 WHERE ID_EMPLEADO = 208;
SELECT * FROM EMPLEADO_COAR;
DELETE FROM EMPLEADO_COAR WHERE ID_EMPLEADO = 208;
COMMIT;

-- ESCENARIO 02:
SELECT * FROM DEPARTAMENTO_COAR;
UPDATE DEPARTAMENTO_COAR SET ID_UBICACION = 3200 WHERE ID_DEPARTAMENTO = 270;
SELECT * FROM DEPARTAMENTO_COAR;
SAVEPOINT PUNTO_A;
DELETE FROM DEPARTAMENTO_COAR WHERE ID_DEPARTAMENTO = 220;
SELECT * FROM DEPARTAMENTO_COAR;
SAVEPOINT PUNTO_B;
INSERT INTO DEPARTAMENTO_COAR VALUES (DEP_COAR_DEP_ID_SEQ.NEXTVAL, 'Logistics', NULL, 3200);
SELECT * FROM DEPARTAMENTO_COAR;
ROLLBACK TO PUNTO_A;
SELECT * FROM DEPARTAMENTO_COAR;
ROLLBACK;
SELECT * FROM DEPARTAMENTO_COAR;

-- ESCENARIO 03:
SELECT * FROM EMPLEADO_COAR;
UPDATE EMPLEADO_COAR SET FECHA_CONTRATACION = '10/09/2004' WHERE ID_EMPLEADO = 206;
SELECT * FROM EMPLEADO_COAR;
COMMIT;

-- ESCENARIO 04:
SELECT * FROM EMPLEADO_COAR;
UPDATE EMPLEADO_COAR SET SALARIO = 4800 WHERE ID_EMPLEADO = 200;
SELECT * FROM EMPLEADO_COAR;
COMMIT;
SELECT * FROM EMPLEADO_COAR;

-- ESCENARIO 05:
SELECT * FROM EMPLEADO_COAR;
UPDATE EMPLEADO_COAR SET SALARIO = 10500 WHERE ID_EMPLEADO = 150;
SELECT * FROM EMPLEADO_COAR;
DELETE FROM EMPLEADO_COAR WHERE ID_EMPLEADO = 207;
SELECT * FROM EMPLEADO_COAR;

CREATE TABLE TABLA_EJEMPLO (
    ID_TABLA_EJEMPLO NUMBER(5) CONSTRAINT TABLA_PK PRIMARY KEY,
    COLUMNA_01 VARCHAR2(20)
);

ROLLBACK;
SELECT * FROM TABLA_EJEMPLO;

-- ####### ESCENARIOS PARA EL ESQUEMA HOTEL_COAR ########
-- USUARIO 01: HOTEL_COAR.

-- ESCENARIO 01:
SELECT * FROM AGENCIA_COAR;
UPDATE AGENCIA_COAR SET NOMBRE = 'AMERICAN EXPRESS' WHERE ID_AGENCIA = 104;
SELECT * FROM AGENCIA_COAR;
DELETE FROM AGENCIA_COAR WHERE ID_AGENCIA = 100;
COMMIT;

-- ESCENARIO 02:
SELECT * FROM HABITACION_COAR;
UPDATE HABITACION_COAR SET NOMBRE = 'Habitaciones comunicada' WHERE ID_HABITACION = 2;
SELECT * FROM HABITACION_COAR;
SAVEPOINT PUNTO_01;
DELETE FROM HABITACION_COAR WHERE ID_HABITACION = 2;
SAVEPOINT PUNTO_02;
INSERT INTO HABITACION_COAR VALUES (HABI_COAR_ID_HABI_SEQ.NEXTVAL, 
                'HABITACION COMUNICADA', 104);
SELECT * FROM HABITACION_COAR;
ROLLBACK TO PUNTO_01;
SELECT * FROM HABITACION_COAR;
ROLLBACK;
SELECT * FROM HABITACION_COAR;                   

-- ESCENARIO 03:
SELECT * FROM HABITACION_COAR;
UPDATE HABITACION_COAR SET NOMBRE = 'HABITACION COMUNICADA' WHERE ID_HABITACION = 2;
SELECT * FROM HABITACION_COAR;
COMMIT;

-- ESCENARIO 04:
SELECT * FROM HABITACION_COAR;
UPDATE HABITACION_COAR SET NOMBRE = 'ESTUDIO' WHERE ID_HABITACION = 2;
SELECT * FROM HABITACION_COAR;
COMMIT;
SELECT * FROM HABITACION_COAR;

-- ESCENARIO 05:
SELECT * FROM HABITACION_COAR;
UPDATE HABITACION_COAR SET NOMBRE = 'HABITACION COMUNICADA' WHERE ID_HABITACION = 2;
SELECT * FROM HABITACION_COAR;
DELETE FROM HABITACION_COAR WHERE ID_HABITACION = 2;
SELECT * FROM HABITACION_COAR;

CREATE TABLE TABLA_EJEMPLO (
    ID_TABLA_EJEMPLO NUMBER(5) CONSTRAINT TABLA_PK PRIMARY KEY,
    COLUMNA_01 VARCHAR2(20)
);

ROLLBACK;
SELECT * FROM HABITACION_COAR;
