-- ACTIVIDAD: CAPITULO_02
-- MATERIA: SISTEMAS DE BASE DE DATOS II.
-- NOMBRE: CRISITAN OMAR ALVARADO RODRIGUEZ.
-- GRUPO: 5"B".

-- 1. = y <>
SELECT * FROM EMPLEADO_COAR WHERE SALARIO = 3000;
SELECT * FROM CLIENTE_COAR WHERE EDAD = 25;
SELECT * FROM CLIENTE_COAR WHERE SEXO = 'M';

SELECT * FROM CLIENTE_COAR WHERE SEXO <> 'F';
SELECT * FROM EMPLEADO_COAR WHERE SALARIO <> 3000;
SELECT * FROM RESERVACION_COAR WHERE ID_EMPLEADO <> 40; 

-- 2. > y <
SELECT * FROM EMPLEADO_COAR WHERE SALARIO > 2000;
SELECT * FROM CLIENTE_COAR WHERE EDAD > 18;
SELECT * FROM HOTEL_COAR WHERE FECHA_CONSTRUCCION > '01-ENE-90';

SELECT * FROM EMPLEADO_COAR WHERE FECHA_CONTRATACION < '10-SEP-2022';
SELECT * FROM RESERVACION_COAR WHERE SUBTOTAL < 3000;
SELECT * FROM CATEGORIA_HOTEL_COAR WHERE IVA < 0.15;

-- 3. >= y <=
SELECT * FROM EMPLEADO_COAR WHERE SALARIO >= 3500;
SELECT * FROM RESERVACION_COAR WHERE DESCUENTO >= 100;
SELECT * FROM CLIENTE_COAR WHERE EDAD >= 30;

SELECT * FROM HOTEL_HABITACION_COAR WHERE CANTIDAD <= 50;
SELECT * FROM EMPLEADO_COAR WHERE SALARIO <= 2500;
SELECT * FROM HOTEL_COAR WHERE FECHA_CONSTRUCCION <= '01-ENE-05';

-- 4. Between y not between.
SELECT * FROM EMPLEADO_COAR WHERE FECHA_CONTRATACION BETWEEN '01/01/2022' AND '10/09/2022';
SELECT * FROM CLIENTE_COAR WHERE EDAD BETWEEN 25 AND 45;
SELECT * FROM EMPLEADO_COAR WHERE SALARIO BETWEEN 2000 AND 3000;

SELECT * FROM HOTEL_COAR WHERE FECHA_CONSTRUCCION NOT BETWEEN '01/01/1990' AND '01/01/2002';
SELECT * FROM RESERVACION_COAR WHERE SUBTOTAL NOT BETWEEN 2500 AND 3000;
SELECT * FROM CLIENTE_COAR WHERE EDAD NOT BETWEEN 20 AND 40;

-- 5. In y not in
SELECT * FROM EMPLEADO_COAR WHERE SALARIO IN (2000,3000,3500);
SELECT * FROM AGENCIA_EMPLEADO_COAR WHERE ID_AGENCIA IN (104);
SELECT * FROM CLIENTE_COAR WHERE EDAD IN (25,40,50);

SELECT * FROM EMPLEADO_COAR WHERE FECHA_CONTRATACION NOT IN ('05/09/2022','10/09/2022');
SELECT * FROM EMPLEADO_COAR WHERE SALARIO NOT IN (3000, 5000);
SELECT * FROM HOTEL_COAR WHERE FECHA_CONSTRUCCION NOT IN ('20/03/1990','25/12/2002');

-- 6. Like y not like (usar en al menos 1 consulta, ESCAPE).
SELECT * FROM EMPLEADO_COAR WHERE CORREO LIKE '%GMAIL%'; 
SELECT * FROM EMPLEADO_COAR WHERE DIRECCION LIKE 'ZAC%'; 
SELECT * FROM CLIENTE_COAR WHERE EDAD LIKE '2_%'; 

SELECT * FROM EMPLEADO_COAR WHERE NOMBRE NOT LIKE '%O%';
SELECT * FROM CLIENTE_COAR WHERE APATERNO NOT LIKE '%A%';
SELECT * FROM EMPLEADO_COAR WHERE AMATERNO NOT LIKE '_O%';

-- 7. Is null e is not null
INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'GARCIA', NULL, 
            'SANTIAGO', 'ANTI@GMAIL.COM', '4928294793', 'ZACATECAS NUM 09', 
            TO_DATE('OCT 02, 2022','MON DD, YYYY'), 3000);

INSERT INTO E_COAR VALUES (EMP_COAR_ID_EMP_SEQ.NEXTVAL, 'MARTINEZ', NULL, 
            'JAVIER', 'JAVI@GMAIL.COM', '4928294832', 'ZACATECAS NUM 590', 
            TO_DATE('OCT 03, 2022','MON DD, YYYY'), 3700);

INSERT INTO C_COAR VALUES (CLI_COAR_ID_CLI_SEQ.NEXTVAL, 'ROBLES', NULL,
            'GABY', 'F', 22, '4926892573', 'ZACATECAS, NUM 234');

COMMIT;

SELECT * FROM CLIENTE_COAR WHERE AMATERNO IS NULL;
SELECT * FROM EMPLEADO_COAR WHERE AMATERNO IS NULL;

SELECT * FROM CLIENTE_COAR WHERE AMATERNO IS NOT NULL;
SELECT * FROM EMPLEADO_COAR WHERE AMATERNO IS NOT NULL;

-- 8. And
SELECT * FROM EMPLEADO_COAR WHERE NOMBRE LIKE '%A%' AND SALARIO > 3000;
SELECT * FROM CLIENTE_COAR WHERE EDAD > 30 AND SEXO = 'M';
SELECT * FROM EMPLEADO_COAR WHERE FECHA_CONTRATACION > '10/09/2022' AND SALARIO >= 2000;

-- 9. Or
SELECT * FROM EMPLEADO_COAR WHERE SALARIO = 3000 OR NOMBRE NOT LIKE '%A%';
SELECT * FROM EMPLEADO_COAR WHERE AMATERNO IS NOT NULL OR FECHA_CONTRATACION = '10/09/2022';
SELECT * FROM CLIENTE_COAR WHERE EDAD > 30 OR SEXO = 'F';

-- 10. Uso de paréntesis.
SELECT * FROM CLIENTE_COAR WHERE (EDAD > 30 OR SEXO = 'M') AND NOMBRE LIKE '%A%';
SELECT * FROM EMPLEADO_COAR WHERE (SALARIO > 2500 OR NOMBRE LIKE '%A%') AND AMATERNO IS NOT NULL;
SELECT * FROM EMPLEADO_COAR WHERE FECHA_CONTRATACION = '10/09/2022'OR (SALARIO > 2500 AND NOMBRE NOT LIKE '%A%');

-- 11. Precedencia de operadores.
SELECT * FROM EMPLEADO_COAR WHERE (SALARIO = 3000) AND NOMBRE LIKE '%A%';
SELECT * FROM EMPLEADO_COAR WHERE SALARIO > 500*7 OR AMATERNO IS NULL;
SELECT * FROM CLIENTE_COAR WHERE EDAD = 25 OR AMATERNO IS NULL AND SEXO = 'M';

-- 12. Order by
SELECT * FROM EMPLEADO_COAR ORDER BY SALARIO;
SELECT * FROM CLIENTE_COAR ORDER BY EDAD DESC;
SELECT * FROM HOTEL_COAR ORDER BY FECHA_CONSTRUCCION;

-- 13. Variables de sustitución con &.
SELECT * FROM EMPLEADO_COAR ORDER BY &COLUMNA_ORDENACION;
SELECT * FROM EMPLEADO_COAR WHERE SALARIO > &CAN_SALARIO;
SELECT * FROM CLIENTE_COAR  WHERE EDAD < &VAR_EDAD;

-- 14. Variables de sustitución con &&.
SELECT * FROM EMPLEADO_COAR WHERE ID_EMPLEADO = &&ID_DEL_EMPLEADO;
SELECT * FROM CLIENTE_COAR WHERE EDAD = &&EDAD_CLIENTE;
SELECT * FROM EMPLEADO_COAR WHERE SALARIO >= &&SALARIO_EMPLEADO;

-- 15. Define y undefine.
DEFINE CONDICION_EDAD = EDAD BETWEEN 25 AND 40;
SELECT * FROM CLIENTE_COAR WHERE &CONDICION_EDAD;
UNDEFINE CONDICION_EDAD;

DEFINE ID_DEL_EMPLEADO = 50;
SELECT * FROM EMPLEADO_COAR WHERE ID_EMPLEADO = &ID_DEL_EMPLEADO;
UNDEFINE ID_DEL_EMPLEADO;

DEFINE CAN_SALARIO = 3000;
SELECT * FROM EMPLEADO_COAR WHERE SALARIO = &CAN_SALARIO;
UNDEFINE CAN_SALARIO;
