-- PRACTICE 07, ACTIVITY 03.
DESC PRODUCT_INFORMATION;
DESC ORDERS;

SELECT DISTINCT SALES_REP_ID FROM ORDERS;

SELECT ORDER_ID, ORDER_DATE, ORDER_TOTAL FROM ORDERS;

SELECT START_DATE, END_DATE FROM HR.JOB_HISTORY;

SELECT PRODUCT_NAME || ' with code: ' || PRODUCT_ID || 'has status of: ' || 
       PRODUCT_STATUS  AS "Product", LIST_PRICE, MIN_PRICE, 
       (LIST_PRICE - MIN_PRICE) "Max Actual Savings",
       ((LIST_PRICE - MIN_PRICE)/LIST_PRICE)*100 "Max Discount %" 
       FROM PRODUCT_INFORMATION;
       
SELECT (4*(22/7))*POWER(3958.759,2) "Earth's Area" FROM DUAL;

-- PRACTICE 08, ACTIVITY 03.
SELECT PRODUCT_NAME, LIST_PRICE, PRODUCT_DESCRIPTION FROM PRODUCT_INFORMATION 
WHERE (PRODUCT_NAME LIKE '%HD%' OR PRODUCT_NAME LIKE '%GP%') AND 
((LIST_PRICE BETWEEN 500 AND 800) AND PRODUCT_NAME LIKE '%HD%')
OR (PRODUCT_NAME LIKE '%GP 1024x768%' or PRODUCT_NAME LIKE '%GP 1280x1024%')
ORDER BY LIST_PRICE DESC;
      
-- PRACTICE 09, ACTIVITY 03.
SELECT PRODUCT_NAME,
       SUBSTR(CATALOG_URL, 17, 6) "SUPPLIER IDENTIFICATION NUMBER"
FROM PRODUCT_INFORMATION WHERE PRODUCT_DESCRIPTION LIKE '%color%' AND
PRODUCT_DESCRIPTION LIKE '%printer%';

-- PRACTICE 10, ACTIVITY 03.
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_EMAIL, DATE_OF_BIRTH, 
  CASE WHEN TRUNC((TO_CHAR(SYSDATE,'DD')-(TO_CHAR(DATE_OF_BIRTH,'DD'))),0) =1 
              AND ((TO_CHAR(SYSDATE,'MM'))-(TO_CHAR(DATE_OF_BIRTH,'MM'))) = 0 THEN 'Yesterday'
       WHEN TRUNC((TO_CHAR(SYSDATE,'DD')-(TO_CHAR(DATE_OF_BIRTH,'DD'))),0) =0 
              AND ((TO_CHAR(SYSDATE,'MM'))-(TO_CHAR(DATE_OF_BIRTH,'MM'))) = 0 THEN 'Today'
       WHEN TRUNC((TO_CHAR(SYSDATE,'DD')-(TO_CHAR(DATE_OF_BIRTH,'DD'))),0) =-1
              AND ((TO_CHAR(SYSDATE,'MM'))-(TO_CHAR(DATE_OF_BIRTH,'MM'))) = 0 THEN 'Tomorrow'
       WHEN TRUNC((TO_CHAR(SYSDATE,'DD')-(TO_CHAR(DATE_OF_BIRTH,'DD'))),0) =-2
              AND ((TO_CHAR(SYSDATE,'MM'))-(TO_CHAR(DATE_OF_BIRTH,'MM'))) = 0 THEN 'Day After Tomorrow'
       WHEN TRUNC((TO_CHAR(SYSDATE,'DD')-(TO_CHAR(DATE_OF_BIRTH,'DD'))),0)>-2 
              AND TRUNC((TO_CHAR(SYSDATE,'DD')-(TO_CHAR(DATE_OF_BIRTH,'DD'))),0) <=-7 
              AND ((TO_CHAR(SYSDATE,'MM'))-(TO_CHAR(DATE_OF_BIRTH,'MM'))) = 0 THEN 'Later this week'
       ELSE 'Not Upcoming Birthday'
END "BIRTHDAY"
FROM CUSTOMERS WHERE 5 IS NOT NULL
ORDER BY TO_CHAR(DATE_OF_BIRTH,'DD'), TO_CHAR(DATE_OF_BIRTH,'MM') ASC;

-- PRACTICE 11, ACTIVITY 03:
SELECT PRODUCT_STATUS, COUNT(*) "QUANTITY PRODUCTS", SUM(LIST_PRICE)
FROM PRODUCT_INFORMATION WHERE PRODUCT_STATUS <> 'orderable'
GROUP BY PRODUCT_STATUS HAVING SUM(LIST_PRICE) > 4000;

-- PRACTICE 12, ACTIVITY 03:
SELECT * FROM PRODUCT_INFORMATION;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;

SELECT CUSTOMERS.CUST_FIRST_NAME, CUSTOMERS.CUST_LAST_NAME, 
       PRODUCT_INFORMATION.PRODUCT_NAME, PRODUCT_INFORMATION.LIST_PRICE 
FROM CUSTOMERS JOIN ORDERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID 
JOIN ORDER_ITEMS ON ORDER_ITEMS.ORDER_ID = ORDERS.ORDER_ID JOIN PRODUCT_INFORMATION 
ON PRODUCT_INFORMATION.PRODUCT_ID = ORDER_ITEMS.PRODUCT_ID WHERE LIST_PRICE > 1000
