-- Practica 05, Actividad 04

CREATE TABLE CUSTOMER (
    ID_CUSTOMER NUMBER(5),
    FIRST_NAME VARCHAR2(35),
    LAST_NAME VARCHAR2(35),
    PHONE VARCHAR2(10)
);

CREATE TABLE CAR (
    ID_CAR NUMBER(5),
    BRAND VARCHAR2(75),
    MODEL VARCHAR2(75),
    KM_TRAVELED NUMBER,
    COLOR VARCHAR2(25)
);

CREATE TABLE HAS_CA (
    ID_CUSTOMER NUMBER(5),
    ID_CAR NUMBER(5)
);

CREATE TABLE SALES_AGENET (
    ID_SALES_AGENET NUMBER(5),
    FIRST_NAME VARCHAR2(75),
    LAST_NAME VARCHAR2(75),
    EMAIL VARCHAR2(75),
    PHONE VARCHAR2(10)
);

CREATE TABLE AUTO_INSURER (
    ID_AI NUMBER(5),
    NAME VARCHAR2(75),
    ADDRESS VARCHAR2(100),
    IN_PHONE VARCHAR2(10)
);

CREATE TABLE HAS_SA (
    ID_SALES_AGENET NUMBER(5),
    ID_AI NUMBER(5)
);

CREATE TABLE POLICY (
    POLICY_NUMBER NUMBER(6),
    ID_CUSTOMER NUMBER(5),
    ID_CAR NUMBER(5),
    ID_SALES_AGENET NUMBER(5),
    ID_AI NUMBER(5),
    START_SATE DATE,
    END_DATE DATE
);

-- INDEX CREATION
CREATE INDEX CUSTOMER_ID_IDX ON CUSTOMER (ID_CUSTOMER);
CREATE INDEX CUSTOMER_NAME_IDX ON CUSTOMER (FIRST_NAME, LAST_NAME);
CREATE INDEX CAR_ID_IDX ON CAR (ID_CAR);
CREATE INDEX HAS_CA_CUS_CAR_IDX ON HAS_CA (ID_CUSTOMER, ID_CAR);
CREATE INDEX SALES_AGENET_ID_IDX ON SALES_AGENET (ID_SALES_AGENET);
CREATE INDEX SALES_AGENET_NAME_IDX ON SALES_AGENET (FIRST_NAME, LAST_NAME);
CREATE INDEX AUTO_INSURER_ID_IDX ON AUTO_INSURER (ID_AI);
CREATE INDEX AUTO_INSURER_NAME_IDX ON AUTO_INSURER (NAME); 
CREATE INDEX HAS_SA_AGEN_AI_IDX ON HAS_SA (ID_SALES_AGENET, ID_AI);
CREATE INDEX POLICY_NUMBER_IDX ON POLICY (POLICY_NUMBER);

-- Creation of constraints

-- PRIMARY KEYS
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID_CUSTOMER);
ALTER TABLE CAR ADD CONSTRAINT CAR_PK PRIMARY KEY (ID_CAR);
ALTER TABLE HAS_CA ADD CONSTRAINT HAS_CA_PK PRIMARY KEY (ID_CUSTOMER, ID_CAR);
ALTER TABLE SALES_AGENET ADD CONSTRAINT SALES_AGENET_PK PRIMARY KEY (ID_SALES_AGENET);
ALTER TABLE AUTO_INSURER ADD CONSTRAINT AUTO_INSURER_PK PRIMARY KEY (ID_AI);
ALTER TABLE HAS_SA ADD CONSTRAINT HAS_SA_PK PRIMARY KEY (ID_SALES_AGENET, ID_AI);
ALTER TABLE POLICY ADD CONSTRAINT POLICY_PK PRIMARY KEY (POLICY_NUMBER);

-- FOREIGN KEYS
ALTER TABLE HAS_CA ADD CONSTRAINT CUSTOMER_HAS_CA_FK FOREIGN KEY (ID_CUSTOMER) 
            REFERENCES CUSTOMER (ID_CUSTOMER);

ALTER TABLE HAS_CA ADD CONSTRAINT CAR_HAS_CA_FK FOREIGN KEY (ID_CAR) 
            REFERENCES CAR (ID_CAR);            

ALTER TABLE HAS_SA ADD CONSTRAINT SALES_AGEN_HAS_SA_FK FOREIGN KEY (ID_SALES_AGENET) 
            REFERENCES SALES_AGENET (ID_SALES_AGENET);

ALTER TABLE HAS_SA ADD CONSTRAINT AI_HAS_SA_FK FOREIGN KEY (ID_AI) 
            REFERENCES AUTO_INSURER (ID_AI);

ALTER TABLE POLICY ADD CONSTRAINT HAS_CA_POLICY_FK FOREIGN KEY (ID_CUSTOMER, ID_CAR) 
            REFERENCES HAS_CA (ID_CUSTOMER, ID_CAR);

ALTER TABLE POLICY ADD CONSTRAINT HAS_SA_POLICY_FK FOREIGN KEY (ID_SALES_AGENET, ID_AI)  
            REFERENCES HAS_SA (ID_SALES_AGENET, ID_AI);

-- CONSTRAINT NOT NULL
ALTER TABLE CUSTOMER MODIFY FIRST_NAME NOT NULL;
ALTER TABLE CUSTOMER MODIFY LAST_NAME NOT NULL;
ALTER TABLE CUSTOMER MODIFY PHONE NOT NULL;
ALTER TABLE CAR MODIFY BRAND NOT NULL;
ALTER TABLE CAR MODIFY MODEL NOT NULL;
ALTER TABLE CAR MODIFY KM_TRAVELED NOT NULL;
ALTER TABLE CAR MODIFY COLOR NOT NULL;
ALTER TABLE SALES_AGENET MODIFY FIRST_NAME NOT NULL;
ALTER TABLE SALES_AGENET MODIFY LAST_NAME NOT NULL;
ALTER TABLE SALES_AGENET MODIFY EMAIL NOT NULL;
ALTER TABLE SALES_AGENET MODIFY PHONE NOT NULL;
ALTER TABLE AUTO_INSURER MODIFY NAME NOT NULL;
ALTER TABLE AUTO_INSURER MODIFY ADDRESS NOT NULL;
ALTER TABLE AUTO_INSURER MODIFY IN_PHONE NOT NULL;
ALTER TABLE POLICY MODIFY START_SATE NOT NULL;
ALTER TABLE POLICY MODIFY END_DATE NOT NULL;

-- CREATE SEQUENCES
CREATE SEQUENCE CUSTOMER_ID_SEQ
                INCREMENT BY 1
                START WITH 1;

CREATE SEQUENCE CAR_ID_SEQ 
                INCREMENT BY 1
                START WITH 1;

CREATE SEQUENCE SALES_AGENET_ID_SEQ  
                INCREMENT BY 1
                START WITH 1;

CREATE SEQUENCE AUTO_INSURER_ID_SEQ 
                INCREMENT BY 1
                START WITH 1;                

CREATE SEQUENCE POLICY_ID_SEQ 
                INCREMENT BY 1
                START WITH 1;

-- CREATE SYNONYMS
CREATE SYNONYM CUS FOR CUSTOMER;
CREATE SYNONYM H_CA FOR HAS_CA;
CREATE SYNONYM SA FOR SALES_AGENET;
CREATE SYNONYM AI FOR AUTO_INSURER;
CREATE SYNONYM H_SA FOR HAS_SA;
CREATE SYNONYM POL FOR POLICY;

