-- Practica 02, Actividad 6

CREATE TABLE PRODUCT_HIERARCHY(
    PRODUCT_CODE CHAR(8),
    PARENT_PRODUCT_CODE CHAR(10),
    PRODUCT_NAME VARCHAR2(20) CONSTRAINT PRO_HI_PN_NN NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR2(40) CONSTRAINT PRO_HIE_PD_NN NOT NULL,
    AMOUNT_REQUIERED NUMBER(6) CONSTRAINT PRO_HI_AR_NN NOT NULL
                                CONSTRAINT PR_AM_CK CHECK (AMOUNT_REQUIERED > 0)
);

SELECT * FROM PRODUCT_HIERARCHY;

CREATE TABLE SUPPLIERS (
    SUPPLIER_CODE CHAR (8),
    SUPPLIER_DETAILS VARCHAR2 (30) CONSTRAINT SUPLIER_SD_NN NOT NULL 
);

SELECT * FROM SUPPLIERS;

CREATE TABLE PRODUCT_SUPPLIERS(
    PRODUCT_CODE CHAR (8),
    SUPPLIER_CODE CHAR (8),
    SUPPLIED_FROM_DATE DATE CONSTRAINT PRO_SU_SFD_NN NOT NULL,
    SUPPLIED_TO_DATE DATE CONSTRAINT PRO_SUP_SD_NN NOT NULL
);

SELECT * FROM PRODUCT_SUPPLIERS;


ALTER TABLE SUPPLIERS ADD STATUS NUMBER(2) CONSTRAINT SUS_ST_NN NOT NULL;
ALTER TABLE SUPPLIERS ADD NAME_SUS VARCHAR2(35) CONSTRAINT SUS_NA_NN NOT NULL;
ALTER TABLE SUPPLIERS ADD CITY INT CONSTRAINT SU_CI_NN NOT NULL;

ALTER TABLE SUPPLIERS DROP COLUMN STATUS;
ALTER TABLE SUPPLIERS RENAME COLUMN CITY TO CITY_ADDREES;
ALTER TABLE SUPPLIERS MODIFY CITY_ADDREES VARCHAR2(50);

SELECT * FROM SUPPLIERS;

DESC SUPPLIERS;

SELECT * FROM SUPPLIERS;
SELECT * FROM PRODUCT_HIERARCHY;
SELECT * FROM PRODUCT_SUPPLIERS;


-- ADD PRIMARY KEY´S
ALTER TABLE PRODUCT_HIERARCHY ADD CONSTRAINT 
                    PRO_HIERARCHY_PK PRIMARY KEY (PRODUCT_CODE);                    

ALTER TABLE SUPPLIERS ADD CONSTRAINT SUPPLIERS_PK PRIMARY KEY (SUPPLIER_CODE);

-- ADD FOREIGN KEY´S
ALTER TABLE PRODUCT_HIERARCHY ADD CONSTRAINT 
                    PRO_HIERARCHY_FK FOREIGN KEY (PARENT_PRODUCT_CODE)
                    REFERENCES PRODUCT_HIERARCHY (PRODUCT_CODE);

ALTER TABLE PRODUCT_SUPPLIERS ADD CONSTRAINT PROH_PROS_FK FOREIGN KEY (PRODUCT_CODE)
                                  REFERENCES PRODUCT_HIERARCHY (PRODUCT_CODE);

ALTER TABLE PRODUCT_SUPPLIERS ADD CONSTRAINT SUS_PROS_FK FOREIGN KEY (SUPPLIER_CODE)
                                  REFERENCES SUPPLIERS (SUPPLIER_CODE);
