-- Practica04, Actividad 2

CREATE TABLE SHOP (
    SHOP_ID NUMBER(4),
    ADDRESS VARCHAR2(100),
    MANGER NUMBER(6)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER(6),
    PNAME VARCHAR2(75),
    SALE_PRICE NUMBER(8,2),
    PURCHASE_PRICE NUMBER(8,2),
    PROVIDER VARCHAR2(75)
);

CREATE TABLE CHANNEL (
    CHANNEL_ID NUMBER(5),
    CNAME VARCHAR2(75)
);

CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER(6),
    EMP_NAME VARCHAR2(35),
    EMP_LASTN VARCHAR2(45),
    BOOS_ID NUMBER(6),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(25),
    BENEFICIARIES VARCHAR2(100)
);

CREATE TABLE SALES (
    SALE_ID NUMBER(6),
    CHANNEL_ID NUMBER(5),
    PRODUCT_ID NUMBER(6),
    SHOP_ID NUMBER(4),
    QUANTITY NUMBER(5),
    EMP_ID NUMBER(6),
    SALE_DATE DATE
);

-- INDICES PARA LAS COLUMNAS DE LAS TABLAS
CREATE INDEX SHOP_ID_IDX ON SHOP (SHOP_ID);
CREATE BITMAP INDEX SHOP_MANAGER_IDX ON SHOP (MANGER);
CREATE BITMAP INDEX PRO_ID_IDX ON PRODUCT (PRODUCT_ID);
CREATE INDEX  PRO_NAME_IDX ON PRODUCT (PNAME);
CREATE INDEX PRO_PRICE_IDX ON PRODUCT (SALE_PRICE, PURCHASE_PRICE);
CREATE INDEX CHANNEL_ID_IDX ON CHANNEL (CHANNEL_ID);
CREATE BITMAP INDEX EMP_ID_IDX ON EMPLOYEE (EMPLOYEE_ID);
CREATE INDEX EMP_NAME_IDX ON EMPLOYEE (EMP_NAME, EMP_LASTN);
CREATE BITMAP INDEX EMP_BOOD_ID_IDX ON EMPLOYEE (BOOS_ID);
CREATE BITMAP INDEX SALES_SALE_ID_IDX ON SALES (SALE_ID);
CREATE INDEX SAL_CHANNEL_ID_IDX ON SALES (CHANNEL_ID);
CREATE BITMAP INDEX SALES_PRO_ID_IDX ON SALES (PRODUCT_ID);
CREATE INDEX SALES_SHOP_ID_IDX ON SALES (SHOP_ID);
CREATE BITMAP INDEX SALES_EMP_ID_IDX ON SALES (EMP_ID);
CREATE BITMAP INDEX SALES_SALE_DATE_IDX ON SALES (SALE_DATE);

-- LLAVES PRIMARIAS
ALTER TABLE SHOP ADD CONSTRAINT SHOP_PK PRIMARY KEY (SHOP_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID);
ALTER TABLE CHANNEL ADD CONSTRAINT CHANNEL_PK PRIMARY KEY (CHANNEL_ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_ID);
ALTER TABLE SALES ADD CONSTRAINT SALES_PK PRIMARY KEY (SALE_ID);

-- COLUMNAS NOT NULL
ALTER TABLE SHOP MODIFY ADDRESS NOT NULL;
ALTER TABLE SHOP MODIFY MANGER NOT NULL;
ALTER TABLE PRODUCT MODIFY PNAME NOT NULL;
ALTER TABLE PRODUCT MODIFY SALE_PRICE NOT NULL;
ALTER TABLE PRODUCT MODIFY PROVIDER;
ALTER TABLE CHANNEL MODIFY CNAME NOT NULL;
ALTER TABLE EMPLOYEE MODIFY EMP_NAME NOT NULL;
ALTER TABLE EMPLOYEE MODIFY EMP_LASTN NOT NULL;
ALTER TABLE EMPLOYEE MODIFY DATE_OF_BIRTH NOT NULL;
ALTER TABLE EMPLOYEE MODIFY GENDER NOT NULL;
ALTER TABLE EMPLOYEE MODIFY BENEFICIARIES NOT NULL;
ALTER TABLE SALES MODIFY QUANTITY NOT NULL;
ALTER TABLE SALES MODIFY SALE_DATE NOT NULL;

-- LLAVES FORANEAS
ALTER TABLE SHOP ADD CONSTRAINT SHOP_MANAGER_FK FOREIGN KEY (MANGER)
                    REFERENCES EMPLOYEE (EMP_ID);   

ALTER TABLE EMPLOYEE ADD CONSTRAINT BOSS_EMP_FK FOREIGN KEY (BOOS_ID)
                     REFERENCES EMPLOYEE (EMP_ID);

ALTER TABLE SALES ADD CONSTRAINT CHANNEL_SALES_FK FOREIGN KEY (CHANNEL_ID)
                      REFERENCES CHANNEL (CHANNEL_ID);  

ALTER TABLE SALES ADD CONSTRAINT PRODUCT_SALES_FK FOREIGN KEY (PRODUCT_ID)
                      REFERENCES PRODUCT (PRODUCT_ID);

ALTER TABLE SALES ADD CONSTRAINT SHOP_SALES_FK FOREIGN KEY (SHOP_ID)
                      REFERENCES SHOP (SHOP_ID);

ALTER TABLE SALES ADD CONSTRAINT EMP_SALES_FK FOREIGN KEY (EMP_ID)
                      REFERENCES EMPLOYEE (EMP_ID); 


-- SECUENCIAS DE LAS TABLAS
CREATE SEQUENCE SHOP_ID_SEQ
                INCREMENT BY 10
                START WITH 10
                MAXVALUE 100;

CREATE SEQUENCE PRODUCT_ID_SEQ
                INCREMENT BY 1
                START WITH 1;

CREATE SEQUENCE CHANNEL_ID_SEQ
                INCREMENT BY 5
                START WITH 100;

CREATE SEQUENCE EMPLOYEE_ID_SEQ
                INCREMENT BY 1
                START WITH 100;

CREATE SEQUENCE SALE_ID_SEQ
                INCREMENT BY 1
                START WITH 1;


-- SINONIMOS PARA LAS TABLAS
CREATE SYNONYM SH FOR SHOP;
CREATE SYNONYM P FOR PRODUCT;
CREATE SYNONYM CH FOR CHANNEL;
CREATE SYNONYM E FOR EMPLOYEE;
CREATE SYNONYM SA FOR SALES;


create table vehicle (
    id_veh number, 
    lic_plates varchar2(10),
    owner_id number
);

create table owner ( 
    owner_id number, 
    surname varchar2(10),
    forename varchar2(10), 
    dateobirth date
);

-- INDICES
CREATE INDEX VEH_ID_IDX ON VEHICLE (ID_VEH);
CREATE INDEX VEH_LIC_PLATES_IDX ON VEHICLE (LIC_PLATES);
CREATE INDEX VEH_PLATES_OWNER_ID_IDX ON VEHICLE (LIC_PLATES, OWNER_ID);
CREATE INDEX OWNER_ID_IDX ON OWNER (OWNER_ID);
CREATE INDEX OWNER_FORENAME_SURNAME_IDX ON OWNER (FORENAME, SURNAME);


-- PRIMARY KEYS
ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_PK PRIMARY KEY (ID_VEH);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_PK PRIMARY KEY (OWNER_ID);

-- CONSTRAINT NOT NULL
ALTER TABLE VEHICLE MODIFY LIC_PLATES NOT NULL;
ALTER TABLE VEHICLE MODIFY OWNER_ID NOT NULL;
ALTER TABLE OWNER MODIFY SURNAME NOT NULL;
ALTER TABLE OWNER MODIFY FORENAME NOT NULL;
ALTER TABLE OWNER MODIFY DATEOBIRTH NOT NULL;

-- FOREIGN KEYS
ALTER TABLE VEHICLE ADD CONSTRAINT OWNER_VEHICLE_FK FOREIGN KEY (OWNER_ID) 
                                    REFERENCES OWNER (OWNER_ID);

-- BORRAR LAS TABLAS VEHICLE Y OWNER
DROP TABLE VEHICLE;
DROP TABLE OWNER;

-- INSERT DATA INTO THE PRODUCT TABLE:
INSERT INTO PRODUCT VALUES (PRODUCT_ID_SEQ.NEXTVAL, 'SODA', 10.50, 7.35, 'COCA-COLA'); 
INSERT INTO PRODUCT VALUES (PRODUCT_ID_SEQ.NEXTVAL, 'BREAD', 5, 6, 'BIMBO'); 
INSERT INTO PRODUCT VALUES (PRODUCT_ID_SEQ.NEXTVAL, 'BISCUITS', 15.60, 12.30, 'GAMESA'); 
INSERT INTO PRODUCT VALUES (PRODUCT_ID_SEQ.NEXTVAL, 'MILK', 18.99, 20, 'LALA'); 

SELECT * FROM PRODUCT;

-- INSERT DATA INTO THE CHANNEL TABLE:
INSERT INTO CHANNEL VALUES (CHANNEL_ID_SEQ.NEXTVAL, 'INTERNET');
INSERT INTO CHANNEL VALUES (CHANNEL_ID_SEQ.NEXTVAL, 'IN SHOP');
INSERT INTO CHANNEL VALUES (CHANNEL_ID_SEQ.NEXTVAL, 'TELEPHONE');

SELECT * FROM CHANNEL;

-- INSERT DATA INTO THE EMPLOYEE TABLE:
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_ID_SEQ.NEXTVAL, 'JUAN', 'RAMIREZ', NULL, 
                            '20/09/1978', 'MALE', 'MARIA RAMIREZ');

INSERT INTO EMPLOYEE VALUES (EMPLOYEE_ID_SEQ.NEXTVAL, 'ANA', 'GARCIA', 100, 
                            '12/02/1989', 'FEMALE', 'MARIO GARCIA');
                            
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_ID_SEQ.NEXTVAL, 'OMAR', 'ALVARADO', 100, 
                            '16/12/2002', 'MALE', 'PEDRO ALVARADO');   

INSERT INTO EMPLOYEE VALUES (EMPLOYEE_ID_SEQ.NEXTVAL, 'MARIA', 'TORRES', 101, 
                            '05/06/2000', 'FEMALE', 'NANCY HERNANDEZ');

INSERT INTO EMPLOYEE VALUES (EMPLOYEE_ID_SEQ.NEXTVAL, 'CARLOS', 'OLVERA', 100, 
                            '08/11/1990', 'MALE', 'ALEX OLVERA');

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMP_ID = 102;

-- INSERT DATA INTO THE SHOP TABLE:
INSERT INTO SHOP VALUES (SHOP_ID_SEQ.NEXTVAL, 'ZACATECAS NUM 102', 100);
INSERT INTO SHOP VALUES (SHOP_ID_SEQ.NEXTVAL, 'FRESNILLO, ZAC NUM 02', 103);
INSERT INTO SHOP VALUES (SHOP_ID_SEQ.NEXTVAL, 'ZACATECAS NUM 34', 101);
INSERT INTO SHOP VALUES (SHOP_ID_SEQ.NEXTVAL, 'JEREZ, ZAC NUM 07', 104);
INSERT INTO SHOP VALUES (SHOP_ID_SEQ.NEXTVAL, 'TEPITO, CDMX NUM 90', 105);

SELECT * FROM SHOP;

-- INSERT DATA INTO THE SALE TABLE:
INSERT INTO SALES VALUES (SALE_ID_SEQ.NEXTVAL, 100, 3, 30, 5, 101, SYSDATE);
INSERT INTO SALES VALUES (SALE_ID_SEQ.NEXTVAL, 105, 2, 50, 5, NULL, SYSDATE);
INSERT INTO SALES VALUES (SALE_ID_SEQ.NEXTVAL, 105, 1, 30, 5, 100, SYSDATE);
INSERT INTO SALES VALUES (SALE_ID_SEQ.NEXTVAL, 100, 4, 60, 5, 101, SYSDATE);
INSERT INTO SALES VALUES (SALE_ID_SEQ.NEXTVAL, 110, 1, 20, 5, 105, SYSDATE);

SELECT * FROM SALES;

COMMIT;